Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub Report_Load()
'If Forms!BulkChange_Form.NoDateLine = -1 Then
 '  Me.AcceptedDateLabel.Visible = False
   'Me.UnitAcceptDate.Visible = False
 '  Else
 '  Me.AcceptedDateLabel.Visible = True
 '  Me.UnitAcceptDate.Visible = True
'End If
End Sub
