SELECT
  DISTINCT vw_ATF_Avail_Signed_FAID.ClientShNm,
  vw_ATF_Avail_Signed_FAID.GroupsIn,
  vw_ATF_Avail_Signed_FAID.SchName,
  vw_ATF_Avail_Signed_FAID.GroupName AS ATFGroupSpecDesc,
  1 AS UnitSpecsInGroup,
  vw_ATF_Avail_Signed_FAID.Spec_UnitQty AS UnitsInGroup,
  vw_ATF_Avail_Signed_FAID.FAID AS GrpFAID,
  -1 AS ExchangeITGroup,
  'Specified Mo' AS ExchangeITType,
  vw_ATF_Avail_Signed_FAID.SchGrp_ExchangeITMonth AS ExchangeITMonth,
  12 AS ExtendITOptionTerm,
  vw_ATF_Avail_Signed_FAID.SchGrp_LeaseTermPrimary AS PrimaryLeaseTerm,
  3 AS PrimaryLeaseNotice,
  'M' AS LeasePymtFreq,
  'Adv' AS LeasePaidAdvArr,
  'Swap' AS SwapIndex,
  vw_ATF_Avail_Signed_FAID.SalesSwapDate AS SwapDate,
  vw_ATF_Avail_Signed_FAID.SalesSwapRate AS SwapRate,
  vw_ATF_Avail_Signed_FAID.SalesSwapTerm AS SwapTermYears,
  vw_ATF_Avail_Signed_FAID.SchGrp_SgrpSalesYield AS SwapYield,
  vw_ATF_Avail_Signed_FAID.SchGrp_SGrpSalesBonus AS SwapBonus,
  10 * 0.01 AS SwapAdjustment,
  CCur([Units_UnitSalesResid]) AS ResidualAvg,
  CCur([UTA_Amount_per_Unit__c]) AS UATPerUnit,
  0 AS PLB,
  'CAPITAL' AS LeaseType,
  1 AS BLCDBasisID,
  2 AS PerDiemBasisID,
  vw_ATF_Avail_Signed_FAID.Deals_dealEstDelDate AS EstDelDate,
  vw_ATF_Avail_Signed_FAID.Total_UTAs_per_ERA__c AS NumUTAs,
  vw_ATF_Avail_Signed_FAID.MilesPerYear,
  vw_ATF_Avail_Signed_FAID.HoursPerYear,
  CCur([Fee_Dollar__c])* [Spec_UnitQty] AS Fee_Projected,
  vw_ATF_Avail_Signed_FAID.SchGrp_SGrpSalesBonus AS Bonus
FROM
  vw_ATF_Avail_Signed_FAID
ORDER BY
  vw_ATF_Avail_Signed_FAID.ClientShNm;
