dbMemo "SQL" ="SELECT 4 AS RevisionNum, #3/30/2026# AS RevisionDate, 'ljohnson' AS SysUser, 'Sc"
    "hedule Inserted into ATLAAS' AS RevisionNote, Clients.clientID AS LeaseeID, Clie"
    "nts.ClientShNm, Clients.clientTaxID, MstrLease.MLID, MstrLease.MLNo, MstrLease.M"
    "LOrig, MstrLease.MLDt, Schedule.SchID, SchGrp.SGrpID, SchGrp.SGrpNO, Schedule.AT"
    "FID, Schedule.ATFSchSpecID, SchGrp.ATFGroupSpecID, Units.ATFUnitSpecID, Count(Un"
    "its.UnitID) AS Units, Max(Units.UnitAcceptDate) AS UnitAcceptDate, Max(Units.Uni"
    "tCofACopy) AS UnitCofACopy, Max(Units.UnitCOABack) AS UnitCOABack, Units.UnitReg"
    "LocationRef, Units.UnitTitleLocationRef, Max(Units.UnitVendorPytDate) AS UnitVen"
    "dorPytDate, Max(Units.UnitActualDelDate) AS UnitActualDelDate, SchGrp.LeaseTermP"
    "rimary, SchGrp.LeaseTermNotice, SchGrp.LeaseType, SchGrp.LeaseExtOption1Term, Sc"
    "hGrp.ExchangeITType, SchGrp.LeasePymtFreq, SchGrp.LeasePaidAdvArr, SchGrp.SGRPPL"
    "B, SchGrp.SGrpSalesIndex, SchGrp.SGrpSalesIndDt, SchGrp.SGprSalesIndYr, SchGrp.S"
    "grpSalesIndRt, SchGrp.SgrpSalesYield, SchGrp.SGrpSalesBonus, SchGrp.SGrpIndex, S"
    "chGrp.SGrpIndDt, SchGrp.SGprIndYr, SchGrp.IndexRate, SchGrp.SgrpYield, SchGrp.SG"
    "rpBonus, SchGrp.SgrpCommInd, SchGrp.PerDiemStartsOn, SchGrp.BLCD, SchGrp.Assigne"
    "e_Bank, Round(Avg(Units.UNITRENT),2) AS UNITRENT, Round(Avg(Units.UNITSRENT),2) "
    "AS UNITSRENT, Round(Avg(Units.FirstExtRent),2) AS FirstExtRent, Round(Avg(Units."
    "MTMRent),2) AS MTMRent, Round(Avg(Units.UnitSalesResid),2) AS UnitSalesResid, Ro"
    "und(Avg(Units.UnitSynResid),2) AS UnitSynResid, Round(Avg(Units.UnitFinalCost),2"
    ") AS UnitFinalCost, Schedule.FSLType, Schedule.ApprovalRequest, Schedule.Approva"
    "lReply, Schedule.SchNo, Schedule.SchShortDesc, Schedule.BankId, Schedule.SchRALO"
    ", Schedule.SchRALB, Schedule.SchRALSigner, Schedule.SchBillAdd, Units.VendorREF,"
    " Max(Units.UnitEstDelDate) AS UnitEstDelDate, Round(Avg(Units.UNITPDRENT),2) AS "
    "UNITPDRENT, Schedule.SchFAID, Units.UnitYr, Units.UnitMake, Units.UnitModel, Uni"
    "ts.UnitType, Units.UnitSubType, Units.Axle, Round(Avg(Units.VendorCost),2) AS Ve"
    "ndorCost\015\012FROM (((Clients INNER JOIN MstrLease ON Clients.clientID = MstrL"
    "ease.Client) INNER JOIN Schedule ON MstrLease.MLID = Schedule.SchMLRef) INNER JO"
    "IN SchGrp ON Schedule.SchID = SchGrp.SGrpSchID) INNER JOIN Units ON SchGrp.SGrpI"
    "D = Units.GroupREF\015\012WHERE Schedule.SchID=3028\015\012GROUP BY Clients.clie"
    "ntID, MstrLease.MLID, MstrLease.MLNo, MstrLease.MLOrig, MstrLease.MLDt, Clients."
    "ClientShNm, Clients.clientTaxID, Schedule.SchID, SchGrp.SGrpID, SchGrp.SGrpNO, S"
    "chedule.ATFID, Schedule.ATFSchSpecID, SchGrp.ATFGroupSpecID, Units.ATFUnitSpecID"
    ", Units.UnitRegLocationRef, Units.UnitTitleLocationRef, SchGrp.LeaseTermPrimary,"
    " SchGrp.LeaseTermNotice, SchGrp.LeaseType, SchGrp.LeaseExtOption1Term, SchGrp.Ex"
    "changeITType, SchGrp.LeasePymtFreq, SchGrp.LeasePaidAdvArr, SchGrp.SGRPPLB, SchG"
    "rp.SGrpSalesIndex, SchGrp.SGrpSalesIndDt, SchGrp.SGprSalesIndYr, SchGrp.SgrpSale"
    "sIndRt, SchGrp.SgrpSalesYield, SchGrp.SGrpSalesBonus, SchGrp.SGrpIndex, SchGrp.S"
    "GrpIndDt, SchGrp.SGprIndYr, SchGrp.IndexRate, SchGrp.SgrpYield, SchGrp.SGrpBonus"
    ", SchGrp.SgrpCommInd, SchGrp.PerDiemStartsOn, SchGrp.BLCD, SchGrp.Assignee_Bank,"
    " Schedule.FSLType, Schedule.ApprovalRequest, Schedule.ApprovalReply, Schedule.Sc"
    "hNo, Schedule.SchShortDesc, Schedule.BankId, Schedule.SchRALO, Schedule.SchRALB,"
    " Schedule.SchRALSigner, Schedule.SchBillAdd, Units.VendorREF, Schedule.SchFAID, "
    "Units.UnitYr, Units.UnitMake, Units.UnitModel, Units.UnitType, Units.UnitSubType"
    ", Units.Axle\015\012HAVING (MstrLease.MLOrig ='FA');\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
Begin
End
