INSERT INTO ATFScheduleRevisions (
  RevisionNum, RevisionDate, SysUser,
  RevisionNote, LeaseeID, ClientShNm,
  clientTaxID, MLID, MLNo, MLOrig, MLDt,
  SchID, SGrpID, SGrpNO, ATFID, ATFSchSpecID,
  ATFGroupSpecID, ATFUnitSpecID, Units,
  UnitAcceptDate, UnitCofACopy, UnitCOABack,
  UnitRegLocationRef, UnitTitleLocationRef,
  UnitVendorPytDate, UnitActualDelDate,
  LeaseTermPrimary, LeaseTermNotice,
  LeaseType, LeaseExtOption1Term,
  ExchangeITType, LeasePymtFreq, LeasePaidAdvArr,
  SGRPPLB, SGrpSalesIndex, SGrpSalesIndDt,
  SGprSalesIndYr, SgrpSalesIndRt,
  SgrpSalesYield, SGrpSalesBonus,
  SGrpIndex, SGrpIndDt, SGprIndYr,
  IndexRate, SgrpYield, SGrpBonus,
  SgrpCommInd, PerDiemStartsOn, BLCD,
  Assignee_Bank, UNITRENT, UNITSRENT,
  FirstExtRent, MTMRent, UnitSalesResid,
  UnitSynResid, UnitFinalCost, FSLType,
  ApprovalRequest, ApprovalReply,
  SchNo, SchShortDesc, BankId, SchRALO,
  SchRALB, SchRALSigner, SchBillAdd,
  VendorREF, UnitEstDelDate, UNITPDRENT,
  SchFAID, UnitYr, UnitMake, UnitModel,
  UnitType, UnitSubType, Axle
)
SELECT
  ATFScheduleRevisionsTemp.RevisionNum,
  ATFScheduleRevisionsTemp.RevisionDate,
  ATFScheduleRevisionsTemp.SysUser,
  ATFScheduleRevisionsTemp.RevisionNote,
  ATFScheduleRevisionsTemp.LeaseeID,
  ATFScheduleRevisionsTemp.ClientShNm,
  ATFScheduleRevisionsTemp.clientTaxID,
  ATFScheduleRevisionsTemp.MLID,
  ATFScheduleRevisionsTemp.MLNo,
  ATFScheduleRevisionsTemp.MLOrig,
  ATFScheduleRevisionsTemp.MLDt,
  ATFScheduleRevisionsTemp.SchID,
  ATFScheduleRevisionsTemp.SGrpID,
  ATFScheduleRevisionsTemp.SGrpNO,
  ATFScheduleRevisionsTemp.ATFID,
  ATFScheduleRevisionsTemp.ATFSchSpecID,
  ATFScheduleRevisionsTemp.ATFGroupSpecID,
  ATFScheduleRevisionsTemp.ATFUnitSpecID,
  ATFScheduleRevisionsTemp.Units,
  ATFScheduleRevisionsTemp.UnitAcceptDate,
  ATFScheduleRevisionsTemp.UnitCofACopy,
  ATFScheduleRevisionsTemp.UnitCOABack,
  ATFScheduleRevisionsTemp.UnitRegLocationRef,
  ATFScheduleRevisionsTemp.UnitTitleLocationRef,
  ATFScheduleRevisionsTemp.UnitVendorPytDate,
  ATFScheduleRevisionsTemp.UnitActualDelDate,
  ATFScheduleRevisionsTemp.LeaseTermPrimary,
  ATFScheduleRevisionsTemp.LeaseTermNotice,
  ATFScheduleRevisionsTemp.LeaseType,
  ATFScheduleRevisionsTemp.LeaseExtOption1Term,
  ATFScheduleRevisionsTemp.ExchangeITType,
  ATFScheduleRevisionsTemp.LeasePymtFreq,
  ATFScheduleRevisionsTemp.LeasePaidAdvArr,
  ATFScheduleRevisionsTemp.SGRPPLB,
  ATFScheduleRevisionsTemp.SGrpSalesIndex,
  ATFScheduleRevisionsTemp.SGrpSalesIndDt,
  ATFScheduleRevisionsTemp.SGprSalesIndYr,
  ATFScheduleRevisionsTemp.SgrpSalesIndRt,
  ATFScheduleRevisionsTemp.SgrpSalesYield,
  ATFScheduleRevisionsTemp.SGrpSalesBonus,
  ATFScheduleRevisionsTemp.SGrpIndex,
  ATFScheduleRevisionsTemp.SGrpIndDt,
  ATFScheduleRevisionsTemp.SGprIndYr,
  ATFScheduleRevisionsTemp.IndexRate,
  ATFScheduleRevisionsTemp.SgrpYield,
  ATFScheduleRevisionsTemp.SGrpBonus,
  ATFScheduleRevisionsTemp.SgrpCommInd,
  ATFScheduleRevisionsTemp.PerDiemStartsOn,
  ATFScheduleRevisionsTemp.BLCD,
  ATFScheduleRevisionsTemp.Assignee_Bank,
  ATFScheduleRevisionsTemp.UNITRENT,
  ATFScheduleRevisionsTemp.UNITSRENT,
  ATFScheduleRevisionsTemp.FirstExtRent,
  ATFScheduleRevisionsTemp.MTMRent,
  ATFScheduleRevisionsTemp.UnitSalesResid,
  ATFScheduleRevisionsTemp.UnitSynResid,
  ATFScheduleRevisionsTemp.UnitFinalCost,
  ATFScheduleRevisionsTemp.FSLType,
  ATFScheduleRevisionsTemp.ApprovalRequest,
  ATFScheduleRevisionsTemp.ApprovalReply,
  ATFScheduleRevisionsTemp.SchNo,
  ATFScheduleRevisionsTemp.SchShortDesc,
  ATFScheduleRevisionsTemp.BankId,
  ATFScheduleRevisionsTemp.SchRALO,
  ATFScheduleRevisionsTemp.SchRALB,
  ATFScheduleRevisionsTemp.SchRALSigner,
  ATFScheduleRevisionsTemp.SchBillAdd,
  ATFScheduleRevisionsTemp.VendorREF,
  ATFScheduleRevisionsTemp.UnitEstDelDate,
  ATFScheduleRevisionsTemp.UNITPDRENT,
  ATFScheduleRevisionsTemp.SchFAID,
  ATFScheduleRevisionsTemp.UnitYr,
  ATFScheduleRevisionsTemp.UnitMake,
  ATFScheduleRevisionsTemp.UnitModel,
  ATFScheduleRevisionsTemp.UnitType,
  ATFScheduleRevisionsTemp.UnitSubType,
  ATFScheduleRevisionsTemp.Axle
FROM
  ATFScheduleRevisionsTemp;
