SELECT
  Client_LPAF.Schedule,
  Client_LPAF.UnitGroup,
  Count(Client_LPAF.UnitID) AS CountOfUnitID,
  Client_LPAF.Make,
  Client_LPAF.Model,
  Client_LPAF.Type,
  Sum(Client_LPAF.[Unit Cost]) AS [SumOfUnit Cost],
  Sum(Client_LPAF.[Child Cost]) AS [SumOfChild Cost],
  Client_LPAF.[Domicile Location],
  Client_LPAF.[Target Delivery],
  Client_LPAF.[Spec Letter],
  Client_LPAF.[Annual Mileage],
  Client_LPAF.[LO Rent],
  Client_LPAF.[Primary Lease Term],
  Client_LPAF.[Synd Rent],
  Client_LPAF.[Lease Extend Term],
  Client_LPAF.[Lease Extend Rent],
  Client_LPAF.MTMRent,
  Client_LPAF.SchID,
  Client_LPAF.ClientShortName,
  Client_LPAF.clientID
FROM
  Client_LPAF
GROUP BY
  Client_LPAF.Schedule,
  Client_LPAF.UnitGroup,
  Client_LPAF.Make,
  Client_LPAF.Model,
  Client_LPAF.Type,
  Client_LPAF.[Domicile Location],
  Client_LPAF.[Target Delivery],
  Client_LPAF.[Spec Letter],
  Client_LPAF.[Annual Mileage],
  Client_LPAF.[LO Rent],
  Client_LPAF.[Primary Lease Term],
  Client_LPAF.[Synd Rent],
  Client_LPAF.[Lease Extend Term],
  Client_LPAF.[Lease Extend Rent],
  Client_LPAF.MTMRent,
  Client_LPAF.SchID,
  Client_LPAF.ClientShortName,
  Client_LPAF.clientID;
