dbMemo "SQL" ="SELECT Cost_ChildParts_AssetID.AssetId, Cost_ChildParts_Pivot_Make.[Dealer Mod\015"
    "\012ECU Programming Make], Cost_ChildParts_Pivot_Cost.[Dealer Mod\015\012ECU Pro"
    "gramming Cost], Cost_ChildParts_Pivot_InvoiceNum.[Dealer Mod\015\012ECU Programm"
    "ing Invoice], Cost_ChildParts_Pivot_InvoiceDate.[Dealer Mod\015\012ECU Programmi"
    "ng Paid], Cost_ChildParts_Pivot_DrawNum.[Dealer Mod\015\012ECU Programming DrawN"
    "um], Cost_ChildParts_Pivot_Make.[Doc Fee\015\012Plate Make], Cost_ChildParts_Piv"
    "ot_Cost.[Doc Fee\015\012Plate Cost], Cost_ChildParts_Pivot_InvoiceNum.[Doc Fee\015"
    "\012Plate Invoice], Cost_ChildParts_Pivot_InvoiceDate.[Doc Fee\015\012Plate Paid"
    "], Cost_ChildParts_Pivot_DrawNum.[Doc Fee\015\012Plate DrawNum], Cost_ChildParts"
    "_Pivot_Make.[Doc Fee 2\015\012Title /Reg Make], Cost_ChildParts_Pivot_Cost.[Doc "
    "Fee 2\015\012Title /Reg Cost], Cost_ChildParts_Pivot_InvoiceNum.[Doc Fee 2\015\012"
    "Title /Reg Invoice], Cost_ChildParts_Pivot_InvoiceDate.[Doc Fee 2\015\012Title /"
    "Reg Paid], Cost_ChildParts_Pivot_DrawNum.[Doc Fee 2\015\012Title /Reg DrawNum], "
    "Cdbl(nz([Dealer Mod\015\012ECU Programming Cost],0))+Cdbl(nz([Doc Fee\015\012Pla"
    "te Cost],0))+Cdbl(nz([Doc Fee 2\015\012Title /Reg Cost],0)) AS ChildPartTotal\015"
    "\012FROM ((((Cost_ChildParts_AssetID LEFT JOIN Cost_ChildParts_Pivot_Make ON Cos"
    "t_ChildParts_AssetID.AssetId = Cost_ChildParts_Pivot_Make.AssetID) LEFT JOIN Cos"
    "t_ChildParts_Pivot_Cost ON Cost_ChildParts_AssetID.AssetId = Cost_ChildParts_Piv"
    "ot_Cost.AssetID) LEFT JOIN Cost_ChildParts_Pivot_InvoiceNum ON Cost_ChildParts_A"
    "ssetID.AssetId = Cost_ChildParts_Pivot_InvoiceNum.AssetID) LEFT JOIN Cost_ChildP"
    "arts_Pivot_InvoiceDate ON Cost_ChildParts_AssetID.AssetId = Cost_ChildParts_Pivo"
    "t_InvoiceDate.AssetID) LEFT JOIN Cost_ChildParts_Pivot_DrawNum ON Cost_ChildPart"
    "s_AssetID.AssetId = Cost_ChildParts_Pivot_DrawNum.AssetID;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
Begin
End
