SELECT
  Clients.clientCompanyName,
  Deals.transTypeRef,
  Deals.dealShortDesc,
  Deals.dealRFPDate,
  Deals.dealRFPDue AS Expr1,
  Deals.dealRFPSent AS Expr2,
  Deals.dealOutcomeDate,
  Deals.dealOutcome,
  Deals.dealOutcomeReason,
  Deals.dealUnitQty,
  Deals.dealMPY,
  Deals.dealTerm,
  Deals.dealUnitPrice,
  Deals.dealGrandTotal,
  Deals.dealEstDelDate,
  Deals.dealDelDate,
  Deals.dealDelThru,
  Deals.CRfinancialsIH,
  Deals.CRFinancialLink,
  Deals.CRGuarantor,
  Deals.CRGtyDate,
  Deals.dealSchedSent,
  Deals.dealSchedBack,
  Deals.dealRALSent,
  Deals.dealRALBack,
  Deals.compAmeriquest AS Expr3,
  Deals.compLeaseplan AS Expr4,
  Deals.compFSL AS Expr5,
  Deals.compPHH AS Expr6,
  Deals.compBank,
  Deals.compOther AS Expr7,
  Deals.FAID,
  Deals.dealSchedNumOrig,
  Deals.dealSchedNum,
  Deals.Proposaltimeline,
  Deals.pipelineOrder
FROM
  Clients
  INNER JOIN Deals ON Clients.clientID = Deals.clientRef
ORDER BY
  Clients.clientCompanyName,
  Deals.transTypeRef,
  Deals.dealOutcomeDate;
