INSERT INTO ExitOptionsGroup_Local (
  AssetID, [Unit#], VIN, Make, ClientShortName,
  Schedule, UnitGroup, ExchTyp, Sts,
  Selected, EOLDate, EOLDatePrimary,
  DaysToEOLPrimary, DaysToEOL, ExchDate,
  DaysToExch, Assignee, ActualOffLeaseDate,
  OffLeaseInd, ODORead, ODOSource,
  ODOReadDate, Garage, LastModified,
  NewClient, NewSchedule, NewGroup,
  NewAssetID, NewInServiceDate, MTMRent,
  ExtendedRent, ActiveRent, RentType,
  ExtendedStart, ExtendedEOL, ReplacedGroupNo,
  ReplacedSchNo, ExchangeITMonth,
  ExchangeITType, ProjRV, LastRent,
  OldSchGrp, OldAssetID, InspectionLinkWeb,
  InspectionLinkLocal, SchIn, EOLQTR,
  EOLMth, EOLDay, EOLYear, EXITQTR,
  EXITMth, EXITDay, EXITYear, ClientID,
  SchID, GroupID, BankId, GarageLocationID,
  ReplacedByScheduleID, ReplacedByGroupID,
  MaxLeaseOptionID, ReplacedSchID,
  ReplacedGroupID, OldSchID, OldGroupID,
  WorkDate, LeaseExp, ActualOffLease,
  ProjOffLease, MLOrig
)
SELECT
  ExitOptionsGroup_EOL.AssetID,
  ExitOptionsGroup_EOL.[Unit#],
  ExitOptionsGroup_EOL.VIN,
  ExitOptionsGroup_EOL.Make,
  ExitOptionsGroup_EOL.ClientShortName,
  ExitOptionsGroup_EOL.Schedule,
  ExitOptionsGroup_EOL.UnitGroup,
  ExitOptionsGroup_EOL.ExchTyp,
  ExitOptionsGroup_EOL.Sts,
  ExitOptionsGroup_EOL.Selected,
  ExitOptionsGroup_EOL.EOLDate,
  ExitOptionsGroup_EOL.EOLDatePrimary,
  ExitOptionsGroup_EOL.DaysToEOLPrimary,
  ExitOptionsGroup_EOL.DaysToEOL,
  ExitOptionsGroup_EOL.ExchDate,
  ExitOptionsGroup_EOL.DaysToExch,
  ExitOptionsGroup_EOL.Assignee,
  ExitOptionsGroup_EOL.ActualOffLeaseDate,
  ExitOptionsGroup_EOL.OffLeaseInd,
  ExitOptionsGroup_EOL.ODORead,
  ExitOptionsGroup_EOL.ODOSource,
  ExitOptionsGroup_EOL.ODOReadDate,
  ExitOptionsGroup_EOL.Garage,
  ExitOptionsGroup_EOL.LastModified,
  ExitOptionsGroup_EOL.NewClient,
  ExitOptionsGroup_EOL.NewSchedule,
  ExitOptionsGroup_EOL.NewGroup,
  ExitOptionsGroup_EOL.NewAssetID,
  ExitOptionsGroup_EOL.NewInServiceDate,
  ExitOptionsGroup_EOL.MTMRent,
  ExitOptionsGroup_EOL.ExtendedRent,
  ExitOptionsGroup_EOL.ActiveRent,
  ExitOptionsGroup_EOL.RentType,
  ExitOptionsGroup_EOL.ExtendedStart,
  ExitOptionsGroup_EOL.ExtendedEOL,
  ExitOptionsGroup_EOL.ReplacedGroupNo,
  ExitOptionsGroup_EOL.ReplacedSchNo,
  ExitOptionsGroup_EOL.ExchangeITMonth,
  ExitOptionsGroup_EOL.ExchangeITType,
  ExitOptionsGroup_EOL.ProjRV,
  ExitOptionsGroup_EOL.LastRent,
  ExitOptionsGroup_EOL.OldSchGrp,
  ExitOptionsGroup_EOL.OldAssetID,
  ExitOptionsGroup_EOL.InspectionLinkWeb,
  ExitOptionsGroup_EOL.InspectionLinkLocal,
  ExitOptionsGroup_EOL.SchIn,
  ExitOptionsGroup_EOL.EOLQTR,
  ExitOptionsGroup_EOL.EOLMth,
  ExitOptionsGroup_EOL.EOLDay,
  ExitOptionsGroup_EOL.EOLYear,
  ExitOptionsGroup_EOL.EXITQTR,
  ExitOptionsGroup_EOL.EXITMth,
  ExitOptionsGroup_EOL.EXITDay,
  ExitOptionsGroup_EOL.EXITYear,
  ExitOptionsGroup_EOL.ClientID,
  ExitOptionsGroup_EOL.SchID,
  ExitOptionsGroup_EOL.GroupID,
  ExitOptionsGroup_EOL.BankId,
  ExitOptionsGroup_EOL.GarageLocationID,
  ExitOptionsGroup_EOL.ReplacedByScheduleID,
  ExitOptionsGroup_EOL.ReplacedByGroupID,
  ExitOptionsGroup_EOL.MaxLeaseOptionID,
  ExitOptionsGroup_EOL.ReplacedSchID,
  ExitOptionsGroup_EOL.ReplacedGroupID,
  ExitOptionsGroup_EOL.OldSchID,
  ExitOptionsGroup_EOL.OldGroupID,
  Now() AS WorkDate,
  ExitOptionsGroup_EOL.LeaseExp,
  ExitOptionsGroup_EOL.ActualOffLease,
  ExitOptionsGroup_EOL.ProjOffLease,
  ExitOptionsGroup_EOL.MLOrig
FROM
  ExitOptionsGroup_EOL;
