SELECT
  E.Client,
  E.Schedule,
  E.UnitGroup,
  E.Assignee,
  E.LeaseType,
  B.BDEX,
  E.BLCD,
  E.AssetID,
  E.UnitNum,
  E.VIN,
  U.UnitYr AS [Year],
  U.UnitMake AS Make,
  U.UnitModel AS Model,
  U.UnitSubType AS SubType,
  U.UnitType AS Type,
  E.CurrRent,
  E.CurrRentType,
  E.uStatus,
  E.EOLPrimary AS [Primary Exp],
  E.DaysToEOL,
  E.Selected AS [Exit Options],
  E.ExtendedStart AS ExtdStart,
  E.OffLeaseProj AS ExtdEnd,
  E.SufSent,
  E.SufBack,
  E.iPassedDate,
  E.ActualOffLease,
  B.LeaseRV,
  B.BookNow,
  B.BV90Days AS [Book 90d],
  E.ODORead,
  E.ODOSource,
  E.ODOReadDate,
  E.Garage,
  E.ExchDate,
  E.DaysToExch,
  E.NewClient,
  E.NewSchedule,
  E.NewGroup,
  E.NewAssetID,
  E.nInServ,
  E.ReplacedSchNo,
  E.ExchangeITMonth,
  E.ExchangeITType,
  E.OldSchGrp,
  E.ClientID,
  E.SchID,
  E.GroupID,
  E.MLOrig,
  E.Selected
FROM
  (
    ExitOptionsGroup_Local AS E
    INNER JOIN Units AS U ON E.AssetID = U.UnitID
  )
  LEFT JOIN vw_BookValue AS B ON E.AssetID = B.AssetID;
