dbMemo "SQL" ="EXEC usp_Ops_ChildPart_Serial"
dbMemo "Connect" ="ODBC;Description=AtlaasCore;DRIVER=ODBC Driver 17 for SQL Server;SERVER=10.1.0.7"
    ",1549;Trusted_Connection=Yes;DATABASE=FleetAdvantage_beSQL;"
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "LogMessages" ="0"
dbByte "Orientation" ="0"
dbBoolean "NoFormat" ="0"
