dbMemo "SQL" ="SELECT Six.ClientShortName As Client, Six.Schedule, Six.UnitGroup as [Group], Si"
    "x.UnitID, Six.Unitnum, PDS.BuyOutCost, PDS.BuyOutDate, PDS.BuyDateEffective AS E"
    "ffectiveBuyOut,InspectionPassed\015\012,Case WHEN InspectionPassed < BuyDateEffe"
    "ctive then 0 else DATEDIFF(dd, Coalesce(Nullif(PDS.BuyDateEffective,''),PDS.BuyO"
    "utDate), COALESCE (PDS.InspectionPassed, GETDATE()))  End AS Days\015\012, PDS.P"
    "erDiemSurrender AS HoldOver , Case WHEN InspectionPassed < BuyDateEffective then"
    " 0 else PDS.PerDiemSurrender * DATEDIFF(dd, Coalesce(Nullif(PDS.BuyDateEffective"
    ",''),PDS.BuyOutDate), COALESCE (PDS.InspectionPassed, GETDATE())) END AS TotalHo"
    "ldOver\015\012, Six.OffLeaseActual AS ActualOffLease, UnitStatus\015\012FROM vw_"
    "SixKeys AS Six INNER JOIN vw_PerDiemSurrender AS PDS ON Six.AssetID = PDS.UnitID"
    " \015\012\015\012"
dbMemo "Connect" ="ODBC;DRIVER=SQL Server;SERVER=FA-PROTEUS\\MSSQL;DATABASE=FleetAdvantage_beSQL;Tr"
    "usted_Connection=yes"
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "LogMessages" ="0"
dbByte "Orientation" ="0"
