SELECT
  FLTSEEK.MLASENTDATE AS Expr1,
  FLTSEEK.[Target Units] AS Expr2,
  FLTSEEK.[Target Sales Volume] AS Expr3,
  FLTSEEK.TOPTEN AS Expr4,
  FLTSEEK.Likelyhood AS Expr5,
  FLTSEEK.SALES AS Expr6,
  FLTSEEK.LIFECYCLE AS Expr7,
  FLTSEEK.ACQUISITIONMODE AS Expr8,
  FLTSEEK.ALIST AS Expr9,
  FLTSEEK.COMMENTS AS Expr10,
  FLTSEEK.ID AS Expr11,
  FLTSEEK.NEWB AS Expr12,
  FLTSEEK.FUP AS Expr13,
  FLTSEEK.WEB AS Expr14,
  FLTSEEK.FAID AS Expr15,
  FLTSEEK.NPTC AS Expr16,
  FLTSEEK.RIN AS Expr17,
  FLTSEEK.MCN AS Expr18,
  FLTSEEK.USDOT AS Expr19,
  FLTSEEK.SCAC AS Expr20,
  FLTSEEK.FILEKEY AS Expr21,
  FLTSEEK.C_TYPECODE AS Expr22,
  FLTSEEK.CTYPEDESC AS Expr23,
  FLTSEEK.COMPANYKEY AS Expr24,
  FLTSEEK.COMPANY AS Expr25,
  FLTSEEK.ADDRESS AS Expr26,
  FLTSEEK.ADDRESS1 AS Expr27,
  FLTSEEK.ADDRESS2 AS Expr28,
  FLTSEEK.CITY AS Expr29,
  FLTSEEK.FIPS AS Expr30,
  FLTSEEK.STATE AS Expr31,
  FLTSEEK.ZIP AS Expr32,
  FLTSEEK.COUNTY AS Expr33,
  FLTSEEK.COMPANYRANK AS Expr34,
  FLTSEEK.[ANNUAL SALES] AS Expr35,
  FLTSEEK.STATENAME AS Expr36,
  FLTSEEK.USCANOTHER AS Expr37,
  FLTSEEK.CALREV AS Expr38,
  FLTSEEK.YEAR_ESTAB AS Expr39,
  FLTSEEK.REVENUE AS Expr40,
  FLTSEEK.ACCTG_CLAS AS Expr41,
  FLTSEEK.CLASS_NO_R AS Expr42,
  FLTSEEK.TOTALVEH AS Expr43,
  FLTSEEK.TOTALVEH_O AS Expr44,
  FLTSEEK.TOTALVEH_L AS Expr45,
  FLTSEEK.STRAIGHT AS Expr46,
  FLTSEEK.STRAIGHT_O AS Expr47,
  FLTSEEK.STRAIGHT_L AS Expr48,
  FLTSEEK.TRACTORS AS Expr49,
  FLTSEEK.TRACTORS_O AS Expr50,
  FLTSEEK.TRACTORS_L AS Expr51,
  FLTSEEK.TRAILERS AS Expr52,
  FLTSEEK.TRAILERS_O AS Expr53,
  FLTSEEK.TRAILERS_L AS Expr54,
  FLTSEEK.TL_LTL AS Expr55,
  FLTSEEK.AUTH_PRINT AS Expr56,
  FLTSEEK.AUTH_B AS Expr57,
  FLTSEEK.AUTH_C AS Expr58,
  FLTSEEK.AUTH_P AS Expr59,
  FLTSEEK.REEFER AS Expr60,
  FLTSEEK.TREEFER AS Expr61,
  FLTSEEK.ETYPECODE1 AS Expr62,
  FLTSEEK.ETYPECODE2 AS Expr63,
  FLTSEEK.ETYPECODE3 AS Expr64,
  FLTSEEK.ETYPECODE4 AS Expr65,
  FLTSEEK.T1N AS Expr66,
  FLTSEEK.T2N AS Expr67,
  FLTSEEK.T1D AS Expr68,
  FLTSEEK.T3N AS Expr69,
  FLTSEEK.T4N AS Expr70,
  FLTSEEK.T2D AS Expr71,
  FLTSEEK.DUPE AS Expr72,
  FLTSEEK.T3D AS Expr73,
  FLTSEEK.T4D AS Expr74,
  FLTSEEK.CLASS8 AS Expr75,
  FLTSEEK.CLASS7 AS Expr76,
  FLTSEEK.CLASS6 AS Expr77,
  FLTSEEK.CLASS345 AS Expr78,
  FLTSEEK.CLASS12 AS Expr79,
  FLTSEEK.VEHMAINT AS Expr80,
  FLTSEEK.SIC AS Expr81,
  FLTSEEK.SICCLASS AS Expr82,
  FLTSEEK.SIC_GROUP AS Expr83,
  FLTSEEK.SIC_GRNAME AS Expr84,
  FLTSEEK.ESTIMEQUIP AS Expr85,
  FLTSEEK.NPAKEY AS Expr86,
  FLTSEEK.LUPD AS Expr87,
  FLTSEEK.int_filesource_id AS Expr88,
  FLTSEEK.int_county_id AS Expr89,
  FLTSEEK.S_RATING AS Expr90,
  FLTSEEK.S_RATE_DATE AS Expr91,
  FLTSEEK.DISTANCE AS Expr92,
  FLTSEEK.NPTC AS Expr93,
  FLTSEEK.CurrentPHH AS Expr94,
  FLTSEEK.CurrentLeaseplan AS Expr95,
  FLTSEEK.CurrentBank AS Expr96,
  FLTSEEK.CurrentFSL AS Expr97,
  FLTSEEK.CurrentCash AS Expr98,
  FLTSEEK.CurrentOther AS Expr99,
  FLTSEEK.CurrentFLEET AS Expr100,
  FLTSEEK.AltAddress AS Expr101,
  FLTSEEK.AltCity AS Expr102,
  FLTSEEK.AltState AS Expr103,
  FLTSEEK.AltZip AS Expr104,
  FLTSEEK.TargetProspect AS Expr105,
  FLTSEEK.MAINTINHOUSE AS Expr106,
  FLTSEEK.MAINTONSITE AS Expr107,
  FLTSEEK.MAINTOFFSITE AS Expr108,
  FLTSEEK.FUELBULK AS Expr109,
  FLTSEEK.FUELCARD AS Expr110,
  FLTSEEK.FSL AS Expr111,
  FLTSEEK.RFPDATE AS Expr112,
  FLTSEEK.DUEDATE AS Expr113,
  FLTSEEK.[EQUIPMENT DESCRIPTION] AS Expr114,
  FLTSEEK.[CAPITAL VALUE] AS Expr115,
  FLTSEEK.STRUCTURE AS Expr116,
  FLTSEEK.TRACRESID AS Expr117,
  FLTSEEK.TREASURYREF AS Expr118,
  FLTSEEK.TREASURYREFDATE AS Expr119,
  FLTSEEK.COMPETITION AS Expr120,
  FLTSEEK.[ANNUAL MILES] AS Expr121,
  FLTSEEK.MILEAGESTUDYCOMPLETE AS Expr122,
  FLTSEEK.MRANALYSIS AS Expr123,
  FLTSEEK.WINNINGBID AS Expr124,
  FLTSEEK.WINNINGLESSOR AS Expr125,
  FLTSEEK.CONTACTTYPE AS Expr126,
  FLTSEEK.SP_MOODYCREDITRATING AS Expr127,
  FLTSEEK.SP_MOODYRATINGDATE AS Expr128,
  FLTSEEK.PRIMCONTACTEXT AS Expr129,
  FLTSEEK.MAINTELEPHONE AS Expr130,
  FLTSEEK.TAXID AS Expr131,
  FLTSEEK.FUPREMINDER AS Expr132,
  FLTSEEK.FUPComplete AS Expr133,
  FLTSEEK.NUMBERDAYCABS AS Expr134,
  FLTSEEK.NUMBERSLEEPERS AS Expr135,
  FLTSEEK.MPYTRACTORS AS Expr136,
  FLTSEEK.MPYSTRAIGHT AS Expr137,
  FLTSEEK.MPYSLEEPER AS Expr138,
  FLTSEEK.MPYDAYCAB AS Expr139,
  FLTSEEK.CREDITREF AS Expr140,
  FLTSEEK.FACREDITRANK AS Expr141,
  FLTSEEK.RPLC_CYCLE AS Expr142,
  FLTSEEK.PREFERED_BRAND AS Expr143,
  FLTSEEK.DELIVERY2008 AS Expr144,
  FLTSEEK.PREBUY2009 AS Expr145,
  FLTSEEK.BUYLEASE AS Expr146,
  FLTSEEK.CALLBACK AS Expr147,
  FLTSEEK.FACUSTPROFILE AS Expr148,
  FLTSEEK.WEBINARDATE AS Expr149,
  FLTSEEK.CREDITTYPE AS Expr150,
  FLTSEEK.MAINTENANCE AS Expr151,
  IIf(
    [FLTSEEK]![CREDITTYPE] Is Null,
    "MissingData",
    IIf(
      [FLTSEEK]![CREDITTYPE] = "Investment Grade",
      25,
      IIf(
        [FLTSEEK]![CREDITTYPE] = "Privately Held",
        10,
        IIf(
          [FLTSEEK]![CREDITTYPE] = "Less Than Investment Grade",
          0, 0
        )
      )
    )
  ) AS ScoreCredit,
  IIf(
    [FLTSEEK]![FACREDITRANK] = "1"
    And [FLTSEEK]![CREDITTYPE] = "Privately Held",
    15,
    IIf(
      [FLTSEEK]![FACREDITRANK] = "2"
      And [FLTSEEK]![CREDITTYPE] = "Privately Held",
      15,
      IIf(
        [FLTSEEK]![FACREDITRANK] = "3"
        And [FLTSEEK]![CREDITTYPE] = "Privately Held",
        15,
        IIf(
          [FLTSEEK]![FACREDITRANK] = "4"
          And [FLTSEEK]![CREDITTYPE] = "Privately Held",
          15,
          IIf(
            [FLTSEEK]![FACREDITRANK] = "1",
            10,
            IIf(
              [FLTSEEK]![FACREDITRANK] = "2",
              10,
              IIf(
                [FLTSEEK]![FACREDITRANK] = "3",
                10,
                IIf(
                  [FLTSEEK]![FACREDITRANK] = "4", 10,
                  0
                )
              )
            )
          )
        )
      )
    )
  ) AS ScoreCredit2,
  IIf(
    [FleetSize] Is Null,
    "MissingData",
    IIf([FleetSize] >= 200, 15, 0)
  ) AS ScoreFleetSize,
  [FLTSEEK]![NUMBERDAYCABS] + [FLTSEEK]![NUMBERSLEEPERS] AS FleetSize,
  [FLTSEEK]![NUMBERDAYCABS] /(
    [FLTSEEK]![NUMBERDAYCABS] + [FLTSEEK]![NUMBERSLEEPERS]
  ) AS PercentDC,
  IIf(
    [PercentDC] Is Null,
    "Missing Data",
    IIf(
      [PercentDC] >= 0.7,
      15,
      IIf([PercentDC] >= 0.5, 10, 0)
    )
  ) AS ScorePercentDC,
  IIf(
    [FLTSEEK]![MPYDAYCAB] < 80000
    Or [FLTSEEK]![MPYDAYCAB] > 120000,
    -10,
    IIf(
      [FLTSEEK]![MPYDAYCAB] Is Null, "MissingData",
      0
    )
  ) AS ScoreDCMiles,
  IIf(
    [FLTSEEK]![MPYSLEEPER] Is Null,
    "MissingData",
    IIf(
      [FLTSEEK]![MPYSLEEPER] > 130000,-10,
      0
    )
  ) AS ScoreSLMiles,
  IIf(
    [FLTSEEK]![MAINTENANCE] Is Null,
    "MissingData",
    IIf(
      [FLTSEEK]![MAINTENANCE] = "In House",
      15,
      IIf(
        [FLTSEEK]![MAINTENANCE] = "3rd Party",
        10, 0
      )
    )
  ) AS ScoreMAINTENANCE,
  IIf(
    [FLTSEEK]![LIFECYCLE] Is Null,
    "MissingData",
    IIf([FLTSEEK]![LIFECYCLE] >= 5, 15, 0)
  ) AS ScoreLIFECYCLE,
  IIf(
    [ACQUISITIONMODE] Is Null,
    "MissingData",
    IIf(
      [ACQUISITIONMODE] = "Purchase",
      15,
      IIf(
        [ACQUISITIONMODE] = "Lease",
        10,
        IIf([ACQUISITIONMODE] = "Full",-10, 0)
      )
    )
  ) AS ScoreACQUISITION,
  [ScoreCredit] + [ScoreCredit2] + [ScoreFleetSize] + [ScorePercentDC] + [ScoreDCMiles] + [ScoreSLMiles] + [ScoreMaintenance] + [ScoreLifecycle] + [ScoreAcquisition] AS TOTALSCORE,
  IIf(
    [TOTALSCORE] >= 80,
    "Qualifies",
    IIf(
      [TOTALSCORE] >= 70, "Review Required",
      "Does Not Qualify"
    )
  ) AS GRADE,
  FLTSEEK.[Target Units] AS Expr152,
  FLTSEEK.[Target Sales Volume] AS Expr153,
  FLTSEEK.TOPTEN AS Expr154,
  FLTSEEK.Likelyhood AS Expr155
FROM
  FLTSEEK
ORDER BY
  FLTSEEK.COMPANY;
