SELECT
  RemarketingReportAllUnits.SourceCompany AS [Account Name],
  RemarketingReportAllUnits.Schedule AS [Lease Sch],
  RemarketingReportAllUnits.UnitGroup AS [Group],
  RemarketingReportAllUnits.UnitNum AS [Customer Unit#],
  RemarketingReportAllUnits.UnitVIN AS VIN,
  RemarketingReportAllUnits.UnitStatus AS [FA Unit Status],
  RemarketingReportAllUnits.UnitYr AS [Year],
  RemarketingReportAllUnits.UnitMake AS Make,
  RemarketingReportAllUnits.UnitModel AS Model,
  RemarketingReportAllUnits.UnitType AS TYPE,
  [ParkedAddress] & " " & [PCity] & ", " & [PState] AS Location,
  RemarketingReportAllUnits.ParkDateProjected AS [Projected Park Date],
  RemarketingReportAllUnits.InspectedDate AS [Inspection Date],
  RemarketingReportAllUnits.InspectionLinkLocal AS [Local Link Insp],
  RemarketingReportAllUnits.InspectionLinkWeb AS [Web Link Insp],
  RemarketingReportAllUnits.Odometer,
  RemarketingReportAllUnits.FMV AS [FA FMV],
  RemarketingReportAllUnits.TargetSalePrice AS [Target Sale Price],
  RemarketingReportAllUnits.UnitID,
  RemarketingReportAllUnits.ClientID,
  RemarketingReportAllUnits.FMV,
  RemarketingReportAllUnits.GainLoss,
  RemarketingReportAllUnits.TargetSalePrice,
  RemarketingReportAllUnits.LocationID,
  RemarketingReportAllUnits.PCity,
  RemarketingReportAllUnits.PState,
  RemarketingReportAllUnits.BuyerID,
  RemarketingReportAllUnits.UnitYr,
  RemarketingReportAllUnits.UnitMake,
  RemarketingReportAllUnits.UnitModel,
  RemarketingReportAllUnits.UnitType,
  RemarketingReportAllUnits.UnitStatus,
  RemarketingReportAllUnits.TitleRecv,
  RemarketingReportAllUnits.InvoiceSent,
  RemarketingReportAllUnits.DaysInAcct AS [Days Since BuyOut],
  RemarketingReportAllUnits.BuyOutDate,
  RemarketingReportAllUnits.[SUF Returned],
  RemarketingReportAllUnits.InvoicePaid
FROM
  RemarketingReportAllUnits;
