SELECT
  RemarketingReportAllUnits.SourceCompany AS [Account Name],
  RemarketingReportAllUnits.Schedule AS [Lease Sch],
  RemarketingReportAllUnits.Unitgroup AS [Group],
  RemarketingReportAllUnits.UnitID AS AssetID,
  RemarketingReportAllUnits.UnitNum AS [Customer Unit#],
  RemarketingReportAllUnits.UnitVIN AS VIN,
  RemarketingReportAllUnits.UnitStatus,
  RemarketingReportAllUnits.RStatus AS InvStatus,
  RemarketingReportAllUnits.UnitYr AS [Year],
  RemarketingReportAllUnits.UnitMake AS Make,
  RemarketingReportAllUnits.UnitModel AS Model,
  RemarketingReportAllUnits.UnitType AS Type,
  RemarketingReportAllUnits.ParkDate,
  RemarketingReportAllUnits.[SUF Sent],
  RemarketingReportAllUnits.[SUF Returned],
  RemarketingReportAllUnits.DaysInInventory AS DaysIn,
  RemarketingReportAllUnits.InspectedDate AS InspnDate,
  RemarketingReportAllUnits.InspectionPassed AS InspPassed,
  RemarketingReportAllUnits.OffLeaseDate,
  RemarketingReportAllUnits.BuyOutDate,
  RemarketingReportAllUnits.InvoicePaid,
  RemarketingReportAllUnits.PayOffRequested AS [PayOff Sent],
  RemarketingReportAllUnits.PayOffReceived AS [PayOff Back],
  RemarketingReportAllUnits.TitleRecvHist AS [Title Recv'd],
  RemarketingReportAllUnits.Buyer,
  RemarketingReportAllUnits.SalesPerson,
  RemarketingReportAllUnits.TargetSalePrice,
  RemarketingReportAllUnits.BuyOut AS [Buy Out Cost],
  RemarketingReportAllUnits.UnitSalePrice,
  RemarketingReportAllUnits.TermPenalty,
  RemarketingReportAllUnits.TotalExpense AS RMKTExpense,
  RemarketingReportAllUnits.UnitProfit,
  RemarketingReportAllUnits.BankPartner,
  RemarketingReportAllUnits.ParkedLocation,
  [ParkedAddress] & " " & [PCity] & ", " & [PState] AS LAddr,
  RemarketingReportAllUnits.PCity,
  RemarketingReportAllUnits.PState,
  RemarketingReportAllUnits.ClientID,
  RemarketingReportAllUnits.BuyerID,
  RemarketingReportAllUnits.UnitID,
  RemarketingReportAllUnits.LocationID,
  RemarketingReportAllUnits.AH_Vin
FROM
  RemarketingReportAllUnits;
