SELECT
  RemarketingReportAllUnits.SourceCompany AS [Account Name],
  RemarketingReportAllUnits.Schedule AS [Lease Sch],
  RemarketingReportAllUnits.UnitGroup AS [Group],
  RemarketingReportAllUnits.UnitNum AS [Customer Unit#],
  RemarketingReportAllUnits.UnitStatus AS [FA Unit Status],
  RemarketingReportAllUnits.UnitYr AS [Year],
  RemarketingReportAllUnits.UnitMake AS Make,
  RemarketingReportAllUnits.UnitModel AS Model,
  RemarketingReportAllUnits.UnitType AS Type,
  RemarketingReportAllUnits.Odometer,
  RemarketingReportAllUnits.Buyer,
  RemarketingReportAllUnits.BuyerType AS Disposition,
  RemarketingReportAllUnits.TargetSalePrice AS [Target Sale Price],
  RemarketingReportAllUnits.UnitSalePrice AS [Sale Price],
  RemarketingReportAllUnits.DaysInInventoryPerAccounting AS [Days Since BuyOut],
  RemarketingReportAllUnits.BuyOutDate,
  RemarketingReportAllUnits.UnitID,
  RemarketingReportAllUnits.ClientID,
  RemarketingReportAllUnits.FMV,
  RemarketingReportAllUnits.GainLoss,
  RemarketingReportAllUnits.TargetSalePrice,
  RemarketingReportAllUnits.LocationID,
  RemarketingReportAllUnits.PCity,
  RemarketingReportAllUnits.PState,
  RemarketingReportAllUnits.BuyerID,
  RemarketingReportAllUnits.UnitYr,
  RemarketingReportAllUnits.UnitMake,
  RemarketingReportAllUnits.UnitModel,
  RemarketingReportAllUnits.UnitType,
  RemarketingReportAllUnits.UnitStatus,
  RemarketingReportAllUnits.TitleRecv,
  RemarketingReportAllUnits.InvoiceSent,
  RemarketingReportAllUnits.[SUF Returned],
  RemarketingReportAllUnits.InvoicePaid,
  RemarketingReportAllUnits.SalesPerson
FROM
  RemarketingReportAllUnits;
