dbMemo "SQL" ="SELECT SU.[Lease No], SU.Lessee, SU.Co_Lessee, SU.SchNo, SU.Group, SU.[Unit No],"
    " SU.Unitvin, SU.Desc, SU.UnitCost, SU.VendorCost, SU.UnitInvoiceNum AS [Invoice "
    "Num], SU.UnitInvoiceDate AS [Invoice Date], SU.UnitInvoicePaid AS [Invoice Paid]"
    ", Cost_ChildParts_Pivot_Make.[Dealer Mod\015\012ECU Programming Make], Cost_Chil"
    "dParts_Pivot_Cost.[Dealer Mod\015\012ECU Programming Cost], Cost_ChildParts_Pivo"
    "t_InvoiceNum.[Dealer Mod\015\012ECU Programming Invoice], Cost_ChildParts_Pivot_"
    "InvoiceDate.[Dealer Mod\015\012ECU Programming Paid], Cost_ChildParts_Pivot_Draw"
    "Num.[Dealer Mod\015\012ECU Programming DrawNum], Cost_ChildParts_Pivot_Make.[Doc"
    " Fee\015\012Plate Make], Cost_ChildParts_Pivot_Cost.[Doc Fee\015\012Plate Cost],"
    " Cost_ChildParts_Pivot_InvoiceNum.[Doc Fee\015\012Plate Invoice], Cost_ChildPart"
    "s_Pivot_InvoiceDate.[Doc Fee\015\012Plate Paid], Cost_ChildParts_Pivot_DrawNum.["
    "Doc Fee\015\012Plate DrawNum], Cost_ChildParts_Pivot_Make.[Doc Fee 2\015\012Titl"
    "e /Reg Make], Cost_ChildParts_Pivot_Cost.[Doc Fee 2\015\012Title /Reg Cost], Cos"
    "t_ChildParts_Pivot_InvoiceNum.[Doc Fee 2\015\012Title /Reg Invoice], Cost_ChildP"
    "arts_Pivot_InvoiceDate.[Doc Fee 2\015\012Title /Reg Paid], Cost_ChildParts_Pivot"
    "_DrawNum.[Doc Fee 2\015\012Title /Reg DrawNum], Cdbl(nz([Dealer Mod\015\012ECU P"
    "rogramming Cost],0))+Cdbl(nz([Doc Fee\015\012Plate Cost],0))+Cdbl(nz([Doc Fee 2\015"
    "\012Title /Reg Cost],0)) AS ChildPartTotal, [UnitCost]+[ChildPartTotal] AS [Unit"
    " OEC], SU.AssetId, SU.Status, SU.FAID, SU.EstiDeliveryDate AS [Est Delv], SU.Act"
    "ualDelDate AS [Actual Delv], SU.DeliveryLoc, SU.InService, SU.[Title Num], SU.Ti"
    "tledState, SU.Location AS Domicile, SU.StreetAddress AS Address, SU.City, SU.Sta"
    "te, SU.Zip, SU.County, SU.InterimBank, SU.InterimDate AS [Interim Funded], SU.In"
    "terimAmt, SU.DrawName, SU.CustodianID, SU.TaxExempt AS [Tax Exempt], SU.UpFront "
    "AS [Up Front], SU.UnitTaxNotes, SU.[State Tax], SU.[County Tax], SU.[City Tax], "
    "SU.[Other Tax], SU.[Loc Tax] AS [Total Tax], SU.LTaxRate AS [ATLAAS TaxRate]\015"
    "\012FROM ScheduleUnitDocs3 AS SU LEFT JOIN Cost_ChildParts_AllTypes ON SU.AssetI"
    "d = Cost_ChildParts_AllTypes.AssetId\015\012WHERE (((SU.AssetID) Is Not Null))\015"
    "\012ORDER BY SU.Group, SU.[Unit No], SU.AssetId;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
Begin
End
