CREATE TABLE [AIMDataTemp] (
  [UnitNumber] VARCHAR (255),
  [VIN] VARCHAR (255),
  [POOL] VARCHAR (255),
  [AGMT] VARCHAR (255),
  [ReadDateMiles] DATETIME,
  [MilesLTD] LONG,
  [MilesRate] VARCHAR,
  [ReadDateHours] DATETIME,
  [HoursLTD] LONG,
  [HoursRate] VARCHAR,
  [StandByDate] DATETIME,
  [StandByRate] VARCHAR,
  [LiftGateStartDate] DATETIME,
  [ReadDateLiftGate] DATETIME,
  [LiftGateCyclesLTD] LONG,
  [LiftGateRate] VARCHAR,
  [UID] VARCHAR (255),
  [UnitType] VARCHAR (255),
  [LeaseType] VARCHAR (255),
  [InServDate] DATETIME,
  [LeaseTerm] VARCHAR (255),
  [LogAct] DATETIME
)
