CREATE TABLE [BTFTemp] (
  [Client] VARCHAR (100),
  [Sch] VARCHAR (50),
  [Grp] VARCHAR (50),
  [Assignee] VARCHAR (50),
  [Funded Date] DATETIME,
  [Group SyndFee] DOUBLE,
  [Portfolio Number] VARCHAR (50),
  [Buyer Order] LONG,
  [AssetID] LONG,
  [Unit Num] VARCHAR (50),
  [VIN] VARCHAR (17),
  [UnitDesc] VARCHAR (216),
  [Unit Status] VARCHAR (5),
  [BLCD] DATETIME,
  [Lease Term] DOUBLE,
  [Term Plus] DOUBLE,
  [Lease Expire] DATETIME,
  [Extend Start] DATETIME,
  [Ext Term] LONG,
  [Extend End] DATETIME,
  [OffLease Actual] DATETIME,
  [UnitOEC] DOUBLE,
  [Payment] CURRENCY,
  [Ext Rent] CURRENCY,
  [Lease RV] CURRENCY,
  [Unit Synd Fee] DOUBLE,
  [Term Penalty] DOUBLE,
  [Rmkt Expense] CURRENCY,
  [Sale Price] CURRENCY,
  [Bank Share] DOUBLE,
  [Fleet Share] DOUBLE,
  [Actual BuyOut Date] DATETIME,
  [Eff BuyOut Date] DATETIME,
  [Actual BuyOut] CURRENCY,
  [BLCD Age Mths] LONG,
  [ArrAdv] LONG,
  [Implicit Rate] DOUBLE,
  [RateAdj] DOUBLE,
  [Book Base] CURRENCY,
  [Exch ROFR] DOUBLE,
  [Exch No ROFR] DOUBLE,
  [Book Adj] DOUBLE,
  [Book Value] DOUBLE,
  [ODO Date] DATETIME,
  [Miles Allowed] DOUBLE,
  [Odometer] LONG,
  [Miles Ovr/Udr] LONG,
  [Over Miles Cost] CURRENCY,
  [IS Share] VARCHAR (1),
  [BankID] LONG,
  [GroupID] LONG,
  [ClientGroupID] LONG
)
