CREATE TABLE [FleetStudyImport_Work] (
  [INDX] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [UnitNumber] VARCHAR (255),
  [OBCUnitNumber] VARCHAR (255),
  [VIN] VARCHAR (255),
  [UnitYear] VARCHAR (255),
  [UnitMake] VARCHAR (255),
  [UnitModel] VARCHAR (255),
  [Type] VARCHAR (255),
  [SubType] VARCHAR (255),
  [InServiceDate] DATETIME,
  [Location] VARCHAR (255),
  [LocationID] LONG,
  [Axle] VARCHAR (255),
  [UnitRent] CURRENCY,
  [Unitcost] CURRENCY,
  [Division] VARCHAR (255),
  [DivisionID] LONG,
  [BankLessor] VARCHAR (255),
  [LeaseStartDate] DATETIME,
  [LeaseTerm] LONG,
  [LeaseEndDate] DATETIME,
  [LeaseType] VARCHAR (255),
  [Odometer] LONG,
  [OdometerDate] DATETIME,
  [Ownership] VARCHAR (255),
  [State] VARCHAR (255),
  [Plate] DATETIME,
  [ReeferHours] LONG,
  [Engine] VARCHAR (255),
  [Trans] VARCHAR (255),
  [ClientID] LONG,
  [ClientGroupID] LONG
)
