CREATE TABLE [GroupAdd_WorkTable] (
  [SGrpID] AUTOINCREMENT,
  [SGrpSchID] LONG,
  [SGrpNO] VARCHAR (50),
  [GroupAddedDate] DATETIME,
  [UnitsInGroup] SHORT,
  [AssigneeBankID] LONG,
  [Assignee_Bank] VARCHAR (50),
  [Assigned_Indicator] VARCHAR (1),
  [AssignmentDate] DATETIME,
  [BPChgLO] SHORT,
  [BPChgLO_Up] DOUBLE,
  [BPChgLO_Down] DOUBLE,
  [BPChgSynd] DOUBLE,
  [BPChgSynd_Up] DOUBLE,
  [BPChgSynd_Down] DOUBLE,
  [BLCD] DATETIME,
  [BLCD_Forecast] DATETIME,
  [BLCD_Projected] DATETIME,
  [BrokerFee] CURRENCY,
  [BuyOutPrice] CURRENCY,
  [BuyOutNote] VARCHAR (50),
  [BuyOutTBD] BIT,
  [CapLeaseBuyOut] CURRENCY,
  [EarlyTermOptional] BIT,
  [EarlyTermNote] VARCHAR (50),
  [ExchangeITGroup] BIT,
  [ExchangeITMonth] SHORT,
  [ExchangeITType] VARCHAR (50),
  [Fee_Projected] CURRENCY,
  [FMVBuyOutOptional] BIT,
  [FundDate] DATETIME,
  [FundDate_Projected] DATETIME,
  [LeaseType] VARCHAR (50),
  [LeaseTermPrimary] VARCHAR,
  [LeasePymtForGroup] CURRENCY,
  [LeasePymtFreq] VARCHAR (50),
  [LeasePaidAdvArr] VARCHAR (50),
  [LeaseTermNotice] SHORT,
  [LRFGroup] DOUBLE,
  [LoanBank] VARCHAR (50),
  [LoanDate] DATETIME,
  [LoanAmount] CURRENCY,
  [LoanType] VARCHAR (50),
  [OrigEquipCost] CURRENCY,
  [SaleDate] DATETIME,
  [SynFee] CURRENCY,
  [SalePrice] CURRENCY,
  [Strips_Projected] SHORT,
  [RebateUnitProjected] CURRENCY,
  [SGrpRtTBD] BIT,
  [LeaseExtOption1Term] SHORT,
  [LeaseExtOption1LRF] DOUBLE,
  [LeaseExtOption1Rent] CURRENCY,
  [BillToAddressID] LONG,
  [SGrpOpt2] SHORT,
  [SGrpO2LRF] DOUBLE,
  [SGrpO2uRent] CURRENCY,
  [SGrpOpt3] SHORT,
  [SGrpO3LRF] DOUBLE,
  [SGrpO3uRent] CURRENCY,
  [SGrpFABill] BIT,
  [SGrpExpDt] DATETIME,
  [SgrpPayoffDt] DATETIME,
  [SGrpEngReb] BIT,
  [SgrpEngMi] LONG,
  [SGprAllow1] LONG,
  [SGprAllow2] LONG,
  [SGprAllow3] LONG,
  [SGprAllow4] LONG,
  [SGprAllow5] LONG,
  [SGprAllow6] LONG,
  [SGrpMH1] VARCHAR (5),
  [SGrpMH2] VARCHAR (5),
  [SGrpMH3] VARCHAR (5),
  [SGrpMH4] VARCHAR (5),
  [SGrpMH5] VARCHAR (5),
  [SGrpMH6] VARCHAR (5),
  [SGrpov1] CURRENCY,
  [SGrpov2] CURRENCY,
  [SGrpov3] CURRENCY,
  [SGrpov4] CURRENCY,
  [SGrpov5] CURRENCY,
  [SGrpov6] CURRENCY,
  [SgrpEq1] VARCHAR (50),
  [SgrpEq2] VARCHAR (50),
  [SgrpEq3] VARCHAR (50),
  [SgrpEq4] VARCHAR (50),
  [SgrpEq5] VARCHAR (50),
  [SgrpEq6] VARCHAR (50),
  [SGPRU/A] VARCHAR (50),
  [AllowedMilesPeriod] VARCHAR (50),
  [SGSL] BIT,
  [SGrpRefR] BIT,
  [SGrpRHr] LONG,
  [SGrpRALO] DATETIME,
  [SGrpRALB] DATETIME,
  [SGrpRALSign] VARCHAR (50),
  [SGRPNoPD] BIT,
  [SGRPINTPD] BIT,
  [SGRPINTRT] DOUBLE,
  [SGrpNoSlv] BIT,
  [SGrpFSLPmt] CURRENCY,
  [PerDiemActual] CURRENCY,
  [PerDiemProjected] CURRENCY,
  [PerDiemStartsOn] LONG,
  [SGrpFSLSch] LONG,
  [SGrpSalesBonus] VARCHAR (50),
  [SGrpSalesIndex] VARCHAR (50),
  [SGrpSalesIndDt] DATETIME,
  [SGprSalesIndYr] SHORT,
  [SgrpSalesIndRt] DOUBLE,
  [SgrpSalesYield] DOUBLE,
  [SgrpSalesSpread] DOUBLE,
  [SGrpBonus] VARCHAR (50),
  [SGrpIndex] VARCHAR (50),
  [SGrpIndDt] DATETIME,
  [SGprIndYr] SHORT,
  [IndexRate] DOUBLE,
  [SgrpYield] DOUBLE,
  [SgrpSpread] DOUBLE,
  [SGrpFSLInd] BIT,
  [SGrpFSLRef] LONG,
  [SGrpFSLTax] CURRENCY,
  [SGRPPLB] BIT,
  [SgrpBnkNo] VARCHAR (50),
  [SGrpFAID] VARCHAR (50),
  [POVendor] LONG,
  [POSentDt] DATETIME,
  [PO2Vendor] LONG,
  [PO2SentDt] DATETIME,
  [PO3Vendor] LONG,
  [PO3SentDt] DATETIME,
  [PO4Vendor] LONG,
  [PO4SentDt] DATETIME,
  [PO5Vendor] LONG,
  [PO5SentDt] DATETIME,
  [PO6Vendor] LONG,
  [PO6SentDt] DATETIME,
  [M-T-MExt] BIT,
  [M-T-MExt1] BIT,
  [M-T-MExt2] BIT,
  [M-T-MExt3] BIT,
  [MaintProv] VARCHAR (50),
  [MaintTerm] SHORT,
  [FAFee] CURRENCY,
  [SalesFSL] CURRENCY,
  [CustPO1] BIT,
  [CustPO2] BIT,
  [CustPO3] BIT,
  [CustPO4] BIT,
  [SGrpIntBnk] VARCHAR (50),
  [SgrpCommInd] VARCHAR (3),
  [SGPRHU/A] VARCHAR (50),
  [AllowedHoursPeriod] VARCHAR (50),
  [AllowedMilesNote] VARCHAR (50),
  [AllowedHoursNote] VARCHAR (50),
  [SgrpTermPenalty] CURRENCY,
  [SGrpExtFSLPmt] CURRENCY,
  [ExtendFSLPymt] CURRENCY,
  [SGrpRSLTPmt] CURRENCY,
  [SgrpFA4Assign] BIT,
  [SgrpCustPmt] SHORT,
  [SgrpSynPenalty] CURRENCY,
  [SgrpSynRebate] CURRENCY,
  [SgrpDesc] VARCHAR (150),
  [WithHeldPymts] LONG,
  [SynMemo] LONGTEXT,
  [MTMRate] DOUBLE,
  [MTMRent] CURRENCY,
  [UnitPctOver] DOUBLE,
  [MilesOver1] DOUBLE,
  [MilesOver2] DOUBLE,
  [MilesOver3] DOUBLE,
  [MilesOverPct1] DOUBLE,
  [MilesOverPct2] DOUBLE,
  [MilesOverPct3] DOUBLE,
  [HoursOver1] DOUBLE,
  [HoursOver2] DOUBLE,
  [HoursOver3] DOUBLE,
  [HoursOverPct1] DOUBLE,
  [HoursOverPct2] DOUBLE,
  [HoursOverPct3] DOUBLE,
  [PONum1] VARCHAR (50),
  [PONum2] VARCHAR (50),
  [PONum3] VARCHAR (50),
  [PONum4] VARCHAR (50),
  [ScheduleGroupPaymentTerm] LONG,
  [LoanSecurityAgmtYN] BIT,
  [OmnibusAgmtYN] BIT,
  [ProgressPymtAgmtYN] BIT,
  [ThirdPartyPayAssgnmtYN] BIT,
  [CustomDocumentNameYN] BIT,
  [CustomDocumentName] VARCHAR (50),
  [BLCDSetBy] VARCHAR (50),
  [HoldbackResidual] CURRENCY,
  [HoldbackConversion] CURRENCY,
  [FAServicer] VARCHAR (50),
  [FAInvoicing] VARCHAR (50),
  [FACollecting] VARCHAR (50),
  [FA3rdPartyPayingAgent] VARCHAR (50),
  [LPAFCost] CURRENCY,
  [SyndMiscLabel1] VARCHAR (50),
  [SyndMiscValue1] CURRENCY,
  [SyndMiscLabel2] VARCHAR (50),
  [SyndMiscValue2] CURRENCY,
  [PVRate] DOUBLE,
  [InterimLoanRate] DOUBLE,
  [ResidualGuaranteeDocYN] BIT,
  [RGDCasualtyYN] BIT,
  [RGDExchangeITYN] BIT,
  [RGDRepurchaseTN] BIT,
  [RGDTerminationYN] BIT,
  [ShortFallAgreementYN] BIT,
  [SFACasualtyYN] BIT,
  [SFAExchangeITYN] BIT,
  [SFARepurchaseTN] BIT,
  [SFATerminationYN] BIT,
  [IndemnificationDocYN] BIT,
  [IDFMileageYN] BIT,
  [IDFLateFeesYN] BIT,
  [LesseeDefaults] VARCHAR (50),
  [LesseeObligations] VARCHAR (50),
  [LesseeDefaultsAll] BIT,
  [LesseeDefaultsCertain] BIT,
  [LesseeObligationsAll] BIT,
  [LesseeObligationsCertain] BIT,
  [LastUpdatedDate] DATETIME,
  [LastUpdatedBy] VARCHAR (50),
  [LastUpdatedField] VARCHAR (50),
  [LastUpdatedValue] VARCHAR (50),
  [UseSpecialRemitGrp] BIT,
  [SpecialRemitAddrGrp] LONGTEXT,
  [ATFGroupSpecID] LONG,
  [ATFID] LONG,
  [BillingInstructions] LONGTEXT,
  [TaxInstructions] LONGTEXT,
  [PVFeesYN] BIT,
  [ServFeePassTroughYN] BIT,
  [DateModified] BINARY,
  [POQuoteNums] LONGTEXT
)
