CREATE TABLE [LocationsTemp] (
  [ClientGroupId] LONG,
  [DivisionID] LONG,
  [LocationType] VARCHAR (50),
  [LocationName] VARCHAR (50),
  [Locationsn] VARCHAR (50),
  [District] VARCHAR (50),
  [LocSubLessee] VARCHAR (50),
  [LocationStreet] VARCHAR (50),
  [LAddrLine1] VARCHAR (50),
  [LAddrLine2] VARCHAR (50),
  [LAddrLine3] VARCHAR (50),
  [LCity] VARCHAR (50),
  [LCounty] VARCHAR (50),
  [LState] VARCHAR (50),
  [LZip] VARCHAR (50),
  [LTaxRate] DOUBLE,
  [LCountry] VARCHAR (50),
  [LPhone] VARCHAR (50),
  [LFax] VARCHAR (50),
  [LEmail] VARCHAR (150),
  [LocObsolete] BIT,
  [LocObsdate] DATETIME,
  [LocObsCmt] VARCHAR (100),
  [oldlocid] LONG,
  [RLocId] SHORT,
  [LocCC] VARCHAR (50),
  [LTaxOption] VARCHAR (50),
  [LocCostCtr] VARCHAR (50),
  [LocABA] VARCHAR (50),
  [LocACH] VARCHAR (50),
  [LocBKACCT] VARCHAR (50),
  [LOCCCC] VARCHAR (255),
  [PortalLocationName] VARCHAR (75),
  [LocationBillingRuleEmail] VARCHAR (100),
  [LocationBillingRuleSubject] VARCHAR (255),
  [LocationBillingRuleBody] VARCHAR (255),
  [LocationBillingRuleAttachmentComments] VARCHAR (100),
  [LocationBillingMethod] VARCHAR (25),
  [LocationBillingRuleAttachmentType] VARCHAR (4),
  [Longitude] VARCHAR,
  [Latitude] VARCHAR
)
