CREATE TABLE [MandRData_Temp] (
  [ClientGroupID] LONG,
  [ClientID] LONG,
  [ActivityMonth] VARCHAR (10),
  [UnitID] LONG,
  [UnitNumber] VARCHAR (50),
  [VIN] VARCHAR (50),
  [FleetCodeDescr] VARCHAR (50),
  [CompanyCodeDescr] VARCHAR (250),
  [CompanyDivision] VARCHAR (50),
  [TypeDescr] VARCHAR (250),
  [VMRS] VARCHAR (3),
  [SystemCodeDescr] VARCHAR (250),
  [RONumber] VARCHAR (50),
  [RODateTime] VARCHAR (10),
  [Usage] LONG,
  [LaborHours] VARCHAR,
  [LaborCost] VARCHAR,
  [OutsideCost] VARCHAR,
  [FluidCost] VARCHAR,
  [PartCost] VARCHAR,
  [TotalCost] VARCHAR,
  [LTD] LONG,
  [INDX] AUTOINCREMENT
)
