CREATE TABLE [Rmkt_WrongStatus] (
  [AssetID] LONG,
  [RmktId] AUTOINCREMENT,
  [UnitRef] LONG,
  [SUF Sent] DATETIME,
  [SUF Returned] DATETIME,
  [ParkDT] DATETIME,
  [BuyOutDate] DATETIME,
  [BuyOutCost] CURRENCY,
  [BuyerRef] LONG,
  [RmktSalePr] CURRENCY,
  [RmktSPRAdj] CURRENCY,
  [TargetSale] CURRENCY,
  [SoldPrice] CURRENCY,
  [InvoiceSentDate] DATETIME,
  [InvoicePaidDate] DATETIME,
  [RmktBOSSent] DATETIME,
  [RmKTBOSRec] DATETIME,
  [RmktTitleRec] DATETIME,
  [RmktTitleSent] DATETIME,
  [BankNotified] DATETIME,
  [Inspected] DATETIME,
  [InspectedBy] LONG,
  [InspChg] CURRENCY,
  [InspResults] VARCHAR (4),
  [RmtTitletoFA] BIT,
  [TitleOut] DATETIME,
  [FATitleBack] DATETIME,
  [MiParked] LONG,
  [HrParked] LONG,
  [RmkSm] VARCHAR (3),
  [RmkLOSupport] CURRENCY,
  [Inspected2] DATETIME,
  [Insp by2] LONG,
  [InspChg2] CURRENCY,
  [InspResults2] VARCHAR (4),
  [InspInv1] VARCHAR (15),
  [InspInv2] VARCHAR (15),
  [FreeStrDays] SHORT,
  [FreeStrexp] DATETIME,
  [AdjBookValue] CURRENCY,
  [RmktAdjNote] VARCHAR (50),
  [PInvReq] BIT,
  [InvoiceRequestDate] DATETIME,
  [PBOS] BIT,
  [RmktDeposit] CURRENCY,
  [RmktDepdt] DATETIME,
  [WhSValue] CURRENCY,
  [Custbookgoal] CURRENCY,
  [FABrkComm] CURRENCY,
  [upsize_ts] BINARY,
  [InspMileage1] LONG,
  [InspMileage2] LONG,
  [PRBOS] BIT,
  [Discount] CURRENCY,
  [DiscountPercentage] DOUBLE,
  [Shipping] CURRENCY,
  [NoScrapSalvageSale] BIT,
  [IFBankID] LONG,
  [IFBankAcctNumber] VARCHAR (30),
  [IFDate] DATETIME,
  [IFAmount] CURRENCY,
  [IFPercentage] DOUBLE,
  [FAAmount] CURRENCY,
  [Commision] CURRENCY
)
