CREATE TABLE [StagingVendorTracking] (
  [Id] DOUBLE CONSTRAINT [Id] PRIMARY KEY UNIQUE NOT NULL,
  [VendorId] DOUBLE,
  [ClientId] VARCHAR (255),
  [PO] VARCHAR (255),
  [FAID] VARCHAR (255),
  [UnitID] DOUBLE,
  [UnitBuildDate] DATETIME,
  [UnitEstDelDate] DATETIME,
  [ActualDelivery] VARCHAR (255),
  [UnitType] VARCHAR (255),
  [UnitYr] DOUBLE,
  [UnitMake] VARCHAR (255),
  [UnitModel] VARCHAR (255),
  [FinalCost] DOUBLE,
  [Axle] VARCHAR (255),
  [VIN] VARCHAR (255),
  [EngineSer] VARCHAR (255),
  [TransSer] VARCHAR (255),
  [FrontAxleSer] VARCHAR (255),
  [RAxleFWDSer] VARCHAR (255),
  [RAxleREARSer] VARCHAR (255),
  [REFENG] VARCHAR (255),
  [COMPRESSS] VARCHAR (255),
  [MICROPROC] VARCHAR (255),
  [ELECDISP] VARCHAR (255),
  [DeliverTo] VARCHAR (255),
  [UnitNotes] VARCHAR (255),
  [IsPilot] VARCHAR (255),
  [DeliveryLocation] DOUBLE,
  [ChildType] VARCHAR (255),
  [ChildMake] VARCHAR (255),
  [ChildYear] DOUBLE,
  [Freight] DOUBLE,
  [ChildPartID] DOUBLE,
  [ImportDate] DATETIME
)
