CREATE TABLE [TaxExceptionsTemp] (
  [ID] AUTOINCREMENT CONSTRAINT [PK_TaxCountiesExceptions] PRIMARY KEY UNIQUE NOT NULL,
  [TaxTypeID] LONG,
  [TaxExceptionTypeID] LONG,
  [ExceptionDescription] LONGTEXT,
  [TaxRule] BIT,
  [TaxRate] VARCHAR,
  [FormURL1] VARCHAR (250),
  [FormURL2] VARCHAR (250),
  [IncludedNAICS] VARCHAR (250),
  [AppliesToTractors] BIT,
  [AppliesToTrailers] BIT,
  [AppliesToStraightTrucks] BIT,
  [WeightLimitMinLbs] LONG,
  [WeightLimitMaxLbs] LONG,
  [TermExceedsMonths] LONG,
  [TaxScript] LONGTEXT,
  [StartsOn] DATETIME,
  [EndsOn] DATETIME,
  [TaxMaxValue] CURRENCY,
  [TaxCitiesID] LONG,
  [TaxStatesID] LONG,
  [TaxCountiesID] LONG,
  [TaxLevel] VARCHAR (255),
  [Mode] VARCHAR (255),
  [TaxExceptionID] LONG,
  [TaxLevelLookupID] LONG
)
