CREATE TABLE [TFR_Work] (
  [DataDate] DATETIME,
  [AccountName] VARCHAR (50),
  [ActualDeliveryDate] DATETIME,
  [AllowType] VARCHAR (50),
  [Assigned_Indicator] VARCHAR (1),
  [AssignmentDate] DATETIME,
  [Axle] LONGTEXT,
  [Bank] VARCHAR (50),
  [BankContract] VARCHAR (101),
  [BankID] LONG,
  [BDEX] VARCHAR (50),
  [BDEXComm] DOUBLE,
  [BDEXCommPct] VARCHAR,
  [BLCD] DATETIME,
  [BLCD_Projected] DATETIME,
  [Bonus] DOUBLE,
  [ClientGroup] VARCHAR (100),
  [ClientGroupId] LONG,
  [clientID] LONG,
  [DealCommission] DOUBLE,
  [DealLOEx] VARCHAR (50),
  [DescAbbrv] VARCHAR (81),
  [EstDelQtr] VARCHAR (7),
  [FAID] VARCHAR (50),
  [FMSS] CURRENCY,
  [FMSSProj] CURRENCY,
  [FMSSTerm] VARCHAR,
  [FMSSTotal] CURRENCY,
  [FundDate] DATETIME,
  [FundDate_Projected] DATETIME,
  [FundingStatus] VARCHAR (17),
  [FYear] LONG,
  [GroupID] LONG,
  [GroupOEC] CURRENCY,
  [GroupPartCost] CURRENCY,
  [IndexRate] DOUBLE,
  [InterimAmount] CURRENCY,
  [InterimExp] CURRENCY,
  [InterimExpPct] VARCHAR,
  [InterimIntRate] DOUBLE,
  [LeaseExp] DATETIME,
  [LeaseTerm] VARCHAR,
  [LeaseTermPrimary] VARCHAR,
  [LeaseType] VARCHAR (50),
  [LOUnitCost] CURRENCY,
  [LoPDUnit] CURRENCY,
  [LoUATUnit] CURRENCY,
  [LRF] VARCHAR,
  [LPAFMonth] VARCHAR (8),
  [LPAFQtr] VARCHAR (7),
  [LPAFYear] LONG,
  [LPAFSigned] DATETIME,
  [Make] LONGTEXT,
  [MaxEstDelDate] DATETIME,
  [MilesAllowed] LONG,
  [MilesAllowedTerm] LONG,
  [MinAcceptedDate] DATETIME,
  [MinPaidDate] DATETIME,
  [Model] LONGTEXT,
  [MYear] LONGTEXT,
  [NetSyndFee] CURRENCY,
  [NetSyndFeeDelta] CURRENCY,
  [NetSyndFeeVar] VARCHAR,
  [NetSyndPct] VARCHAR,
  [NetSyndProj] CURRENCY,
  [NetTotalFee] DOUBLE,
  [NetTotalPct] VARCHAR,
  [NPV] CURRENCY,
  [NPVDelta] CURRENCY,
  [NPVPct] VARCHAR,
  [NPVProj] CURRENCY,
  [NPVVar] VARCHAR,
  [NumStrips] LONG,
  [OEC] CURRENCY,
  [OECPerUnit] CURRENCY,
  [PDDays] LONG,
  [PDDaysAvg] LONG,
  [PDRent] CURRENCY,
  [PDRentActual] CURRENCY,
  [PDRentDelta] CURRENCY,
  [PDRentPct] VARCHAR,
  [PDRentProj] CURRENCY,
  [PDRentSynd] CURRENCY,
  [PDRentVar] VARCHAR,
  [PmtAmt] CURRENCY,
  [PmtAmtFMSS] CURRENCY,
  [PVRate] DOUBLE,
  [Residual] CURRENCY,
  [RV] CURRENCY,
  [RVPct] VARCHAR,
  [RVProj] CURRENCY,
  [RVPerUnit] CURRENCY,
  [SalePrice] CURRENCY,
  [Sch_Grp] VARCHAR (103),
  [Schedule] VARCHAR (50),
  [ScheduleGroupPaymentTerm] LONG,
  [SchIn] DATETIME,
  [SchID] LONG,
  [SchRent] CURRENCY,
  [ServFeePassTroughYN] BIT,
  [SGrpBonus] VARCHAR (50),
  [SGrpID] LONG,
  [SLB] VARCHAR (1),
  [Spread] DOUBLE,
  [SpreadIRR] DOUBLE,
  [SpreadProj] DOUBLE,
  [StillActive] LONG,
  [StripRent] CURRENCY,
  [StripRentPct] VARCHAR,
  [SubType] LONGTEXT,
  [SWAP] DOUBLE,
  [SyndFee] CURRENCY,
  [SyndFeeDelta] CURRENCY,
  [SyndFeePct] VARCHAR,
  [SyndFeeProj] CURRENCY,
  [SyndFeeSynd] CURRENCY,
  [SyndFeeVar] VARCHAR,
  [SyndRent] CURRENCY,
  [SyndFeeVendorPct] VARCHAR,
  [TargetFundDate] DATETIME,
  [TargetFundMonth] VARCHAR (8),
  [TermPenalty] CURRENCY,
  [TermPenaltyDelta] CURRENCY,
  [TermPenaltyPct] VARCHAR,
  [TermPenaltyProj] CURRENCY,
  [TermPenaltySynd] CURRENCY,
  [TermPenaltyVar] VARCHAR,
  [TotalFee] CURRENCY,
  [TotalFeeDelta] CURRENCY,
  [TotalFeePct] VARCHAR,
  [TotalFeeProj] CURRENCY,
  [TotalFeeVar] VARCHAR,
  [TotalVendorCost] CURRENCY,
  [Type] LONGTEXT,
  [UnitCount] SHORT,
  [UnitDesc] LONGTEXT,
  [UnitGroup] VARCHAR (50),
  [UTA] CURRENCY,
  [UTADelta] CURRENCY,
  [UTApct] VARCHAR,
  [UTAProj] CURRENCY,
  [UTASynd] CURRENCY,
  [UTAVar] VARCHAR,
  [VendorCostUnit] CURRENCY,
  [SwapType] VARCHAR (50),
  [Yield] DOUBLE,
  [YieldIRR] DOUBLE,
  [SyndFeePlus] CURRENCY,
  [LoPDPct] VARCHAR,
  [LoSyndPct] VARCHAR,
  [LoSyndStripPct] VARCHAR,
  [LoSyndNetPct] VARCHAR,
  [LoTermPenaltyPct] VARCHAR,
  [LoUTAPct] VARCHAR,
  [LoTotalFeePct] VARCHAR,
  [LoAmount] CURRENCY,
  [SwapTypeLO] VARCHAR (50),
  [LOIndexRate] DOUBLE,
  [SchLRF] VARCHAR,
  [LOYield] DOUBLE,
  [LOBonus] VARCHAR (50),
  [LoSyndNet] CURRENCY,
  [RVVendorPct] VARCHAR,
  [RVLOUnit] CURRENCY,
  [RVLOUnitPct] VARCHAR,
  [LORent] CURRENCY,
  [RVProjPct] CURRENCY,
  [UnitCost] CURRENCY,
  [ODORange] VARCHAR (12)
)
