CREATE TABLE [Units_Temp] (
  [ID] AUTOINCREMENT CONSTRAINT [ID] PRIMARY KEY UNIQUE NOT NULL,
  [AssetID] DOUBLE,
  [BuildDate] DATETIME,
  [PO] VARCHAR (255),
  [SCH] DOUBLE,
  [Group] VARCHAR (255)
)
