Version =20
VersionRequired =20
Begin Form
    RecordSelectors = NotDefault
    NavigationButtons = NotDefault
    DividingLines = NotDefault
    AllowDesignChanges = NotDefault
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridX =24
    GridY =24
    Width =13392
    DatasheetFontHeight =11
    ItemSuffix =437
    Left =9900
    Top =6735
    Right =23490
    Bottom =10365
    RecSrcDt = Begin
        0xf4336b358db6e540
    End
    RecordSource ="SELECT * FROM BuyersOrderUnits WHERE (((BuyersOrderUnits.BuyersOrderID)=[Forms]!"
        "[BuyersForm]![RemarketingInvoiceRequest_Sub].[Form]![InvoiceRequestID]));"
    DatasheetFontName ="Calibri"
    AllowDatasheetView =0
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
    Begin
        Begin Label
            BackStyle =0
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin CommandButton
            FontSize =11
            FontWeight =400
            FontName ="Calibri"
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            UseTheme =1
            Shape =1
            Gradient =12
            BackThemeColorIndex =4
            BackTint =60.0
            BorderLineStyle =0
            BorderThemeColorIndex =4
            BorderTint =60.0
            ThemeFontIndex =1
            HoverThemeColorIndex =4
            HoverTint =40.0
            PressedThemeColorIndex =4
            PressedShade =75.0
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
        End
        Begin TextBox
            AddColon = NotDefault
            FELineBreak = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            AsianLineBreak =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin EmptyCell
            Height =240
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin FormHeader
            Height =552
            Name ="FormHeader"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =2
            BackTint =60.0
            Begin
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Top =276
                    Width =705
                    Height =276
                    FontSize =9
                    ForeColor =16777215
                    Name ="Label12"
                    Caption ="AssetID"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedTop =276
                    LayoutCachedWidth =705
                    LayoutCachedHeight =552
                    RowStart =1
                    RowEnd =1
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =17
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =7356
                    Top =276
                    Width =1008
                    Height =276
                    FontSize =9
                    ForeColor =16777215
                    Name ="Label19"
                    Caption ="Sent"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =7356
                    LayoutCachedTop =276
                    LayoutCachedWidth =8364
                    LayoutCachedHeight =552
                    RowStart =1
                    RowEnd =1
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =17
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =3
                    Left =8364
                    Top =276
                    Width =1080
                    Height =276
                    FontSize =9
                    ForeColor =16777215
                    Name ="Label18"
                    Caption ="Target Price"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8364
                    LayoutCachedTop =276
                    LayoutCachedWidth =9444
                    LayoutCachedHeight =552
                    RowStart =1
                    RowEnd =1
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =17
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =3816
                    Top =276
                    Width =3540
                    Height =276
                    FontSize =9
                    ForeColor =16777215
                    Name ="Label177"
                    Caption ="Desc"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =3816
                    LayoutCachedTop =276
                    LayoutCachedWidth =7356
                    LayoutCachedHeight =552
                    RowStart =1
                    RowEnd =1
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =17
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =1
                    BackStyle =0
                    IMESentenceMode =3
                    Left =3816
                    Width =3540
                    Height =270
                    ColumnOrder =2
                    FontSize =9
                    FontWeight =700
                    TabIndex =1
                    ForeColor =16777215
                    Name ="Text239"
                    ControlSource ="=\"Units: \" & Count([UnitID])"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =3816
                    LayoutCachedWidth =7356
                    LayoutCachedHeight =270
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =2
                    BackShade =75.0
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =17
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =1776
                    Top =276
                    Width =2040
                    Height =276
                    FontSize =9
                    ForeColor =16777215
                    Name ="Label1"
                    Caption ="VIN"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =1776
                    LayoutCachedTop =276
                    LayoutCachedWidth =3816
                    LayoutCachedHeight =552
                    RowStart =1
                    RowEnd =1
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =17
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =708
                    Top =276
                    Width =1068
                    Height =276
                    FontSize =9
                    ForeColor =16777215
                    Name ="UnitNumLbl"
                    Caption ="UnitNum"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =708
                    LayoutCachedTop =276
                    LayoutCachedWidth =1776
                    LayoutCachedHeight =552
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =17
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =9444
                    Top =276
                    Width =360
                    Height =276
                    FontSize =9
                    ForeColor =16777215
                    Name ="UnitStatusLbl"
                    Caption ="Sts"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9444
                    LayoutCachedTop =276
                    LayoutCachedWidth =9804
                    LayoutCachedHeight =552
                    RowStart =1
                    RowEnd =1
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =17
                End
                Begin Label
                    BackStyle =1
                    OverlapFlags =85
                    TextAlign =2
                    Left =9816
                    Top =276
                    Width =1080
                    Height =276
                    FontSize =9
                    BackColor =373753
                    ForeColor =0
                    Name ="SalePriceLbl"
                    Caption ="Sale Price"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9816
                    LayoutCachedTop =276
                    LayoutCachedWidth =10896
                    LayoutCachedHeight =552
                    RowStart =1
                    RowEnd =1
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    BackThemeColorIndex =-1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =17
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =10896
                    Top =276
                    Width =360
                    Height =276
                    FontSize =9
                    ForeColor =16777215
                    Name ="SPlbl"
                    Caption ="SP"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10896
                    LayoutCachedTop =276
                    LayoutCachedWidth =11256
                    LayoutCachedHeight =552
                    RowStart =1
                    RowEnd =1
                    ColumnStart =8
                    ColumnEnd =8
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =17
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =11256
                    Top =276
                    Width =1008
                    Height =276
                    FontSize =9
                    ForeColor =16777215
                    Name ="PaidDatelbl"
                    Caption ="Paid"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =11256
                    LayoutCachedTop =276
                    LayoutCachedWidth =12264
                    LayoutCachedHeight =552
                    RowStart =1
                    RowEnd =1
                    ColumnStart =9
                    ColumnEnd =9
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =17
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =1
                    BackStyle =0
                    IMESentenceMode =3
                    Left =1776
                    Width =2040
                    Height =270
                    ColumnOrder =3
                    FontSize =9
                    FontWeight =700
                    ForeColor =16777215
                    Name ="BuyersOrderID"
                    ControlSource ="BuyersOrderID"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =1776
                    LayoutCachedWidth =3816
                    LayoutCachedHeight =270
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    BackThemeColorIndex =2
                    BackShade =75.0
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =17
                    Begin
                        Begin Label
                            OverlapFlags =85
                            TextAlign =1
                            Left =708
                            Width =1068
                            Height =270
                            FontSize =9
                            FontWeight =700
                            ForeColor =16777215
                            Name ="Label413"
                            Caption ="Buyer Order:"
                            GroupTable =17
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =708
                            LayoutCachedWidth =1776
                            LayoutCachedHeight =270
                            ColumnStart =1
                            ColumnEnd =1
                            LayoutGroup =1
                            BackThemeColorIndex =2
                            BackShade =75.0
                            BorderThemeColorIndex =1
                            BorderTint =100.0
                            BorderShade =65.0
                            ForeThemeColorIndex =-1
                            ForeTint =100.0
                            GroupTable =17
                        End
                    End
                End
                Begin EmptyCell
                    Left =9444
                    Width =360
                    Height =270
                    Name ="EmptyCell403"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9444
                    LayoutCachedWidth =9804
                    LayoutCachedHeight =270
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin EmptyCell
                    Left =10896
                    Width =360
                    Height =270
                    Name ="EmptyCell405"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10896
                    LayoutCachedWidth =11256
                    LayoutCachedHeight =270
                    ColumnStart =8
                    ColumnEnd =8
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin EmptyCell
                    Left =11256
                    Width =1008
                    Height =270
                    Name ="EmptyCell406"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =11256
                    LayoutCachedWidth =12264
                    LayoutCachedHeight =270
                    ColumnStart =9
                    ColumnEnd =9
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin EmptyCell
                    Left =13032
                    Width =360
                    Height =270
                    Name ="EmptyCell407"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =13032
                    LayoutCachedWidth =13392
                    LayoutCachedHeight =270
                    ColumnStart =11
                    ColumnEnd =11
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin EmptyCell
                    Width =705
                    Height =270
                    Name ="EmptyCell415"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedWidth =705
                    LayoutCachedHeight =270
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin EmptyCell
                    Left =7356
                    Width =1008
                    Height =270
                    Name ="EmptyCell416"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =7356
                    LayoutCachedWidth =8364
                    LayoutCachedHeight =270
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin CommandButton
                    OverlapFlags =85
                    TextFontCharSet =2
                    TextFontFamily =2
                    Left =13032
                    Top =276
                    Width =360
                    Height =276
                    FontSize =10
                    TabIndex =4
                    ForeColor =1643706
                    Name ="RemoveAllUnits"
                    Caption ="ý"
                    OnClick ="[Event Procedure]"
                    FontName ="Wingdings"
                    ControlTipText ="Remove All Units from Buyer's Order"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =13032
                    LayoutCachedTop =276
                    LayoutCachedWidth =13392
                    LayoutCachedHeight =552
                    RowStart =1
                    RowEnd =1
                    ColumnStart =11
                    ColumnEnd =11
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    Shape =0
                    Gradient =0
                    BackThemeColorIndex =9
                    OldBorderStyle =0
                    BorderThemeColorIndex =1
                    BorderTint =100.0
                    ThemeFontIndex =-1
                    HoverColor =1643706
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedThemeColorIndex =9
                    HoverForeColor =16777215
                    HoverForeThemeColorIndex =-1
                    HoverForeTint =100.0
                    PressedForeColor =1643706
                    PressedForeThemeColorIndex =-1
                    PressedForeTint =100.0
                    GroupTable =17
                    QuickStyle =31
                    QuickStyleMask =-885
                    Begin
                        Begin Label
                            BackStyle =1
                            OverlapFlags =85
                            TextAlign =2
                            Left =12276
                            Top =276
                            Width =756
                            Height =276
                            FontSize =9
                            BackColor =3381759
                            ForeColor =0
                            Name ="Label430"
                            Caption ="Waranty"
                            GroupTable =17
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =12276
                            LayoutCachedTop =276
                            LayoutCachedWidth =13032
                            LayoutCachedHeight =552
                            RowStart =1
                            RowEnd =1
                            ColumnStart =10
                            ColumnEnd =10
                            LayoutGroup =1
                            BackThemeColorIndex =-1
                            ForeThemeColorIndex =-1
                            ForeTint =100.0
                            GroupTable =17
                        End
                    End
                End
                Begin TextBox
                    Visible = NotDefault
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =8364
                    Width =1080
                    Height =270
                    ColumnOrder =0
                    FontSize =9
                    TabIndex =2
                    Name ="Sent"
                    ControlSource ="InvoiceSentDate"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =8364
                    LayoutCachedWidth =9444
                    LayoutCachedHeight =270
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin TextBox
                    Visible = NotDefault
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9816
                    Width =1080
                    Height =270
                    ColumnOrder =1
                    FontSize =9
                    TabIndex =3
                    Name ="Paid"
                    ControlSource ="InvoicePaidDate"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9816
                    LayoutCachedWidth =10896
                    LayoutCachedHeight =270
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin EmptyCell
                    Left =12276
                    Width =756
                    Height =270
                    Name ="EmptyCell434"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =12276
                    LayoutCachedWidth =13032
                    LayoutCachedHeight =270
                    ColumnStart =10
                    ColumnEnd =10
                    LayoutGroup =1
                    GroupTable =17
                End
            End
        End
        Begin Section
            Height =240
            Name ="Detail"
            AlternateBackColor =16777215
            BackThemeColorIndex =1
            Begin
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =1776
                    Width =2040
                    FontSize =9
                    TabIndex =2
                    Name ="UnitVIN"
                    ControlSource ="UnitVIN"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =1776
                    LayoutCachedWidth =3816
                    LayoutCachedHeight =240
                    RowStart =2
                    RowEnd =2
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin TextBox
                    Locked = NotDefault
                    FontUnderline = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Width =705
                    FontSize =9
                    Name ="UnitID"
                    ControlSource ="UnitId"
                    OnDblClick ="[Event Procedure]"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedWidth =705
                    LayoutCachedHeight =240
                    RowStart =2
                    RowEnd =2
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =2
                    IMESentenceMode =3
                    Left =9444
                    Width =360
                    ColumnWidth =1380
                    FontSize =9
                    FontWeight =700
                    TabIndex =6
                    Name ="UnitStatus"
                    ControlSource ="STS"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9444
                    LayoutCachedWidth =9804
                    LayoutCachedHeight =240
                    RowStart =2
                    RowEnd =2
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin TextBox
                    OverlapFlags =93
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9816
                    Width =1080
                    FontSize =9
                    TabIndex =7
                    Name ="SalePrice"
                    ControlSource ="SalePrice"
                    Format ="$#,##0.00;($#,##0.00)"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9816
                    LayoutCachedWidth =10896
                    LayoutCachedHeight =240
                    RowStart =2
                    RowEnd =2
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    BorderThemeColorIndex =6
                    BorderShade =50.0
                    GroupTable =17
                    CurrencySymbol ="$"
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =87
                    TextAlign =2
                    IMESentenceMode =3
                    Left =10896
                    Width =360
                    FontSize =9
                    TabIndex =8
                    Name ="SP"
                    ControlSource ="SP"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =10896
                    LayoutCachedWidth =11256
                    LayoutCachedHeight =240
                    RowStart =2
                    RowEnd =2
                    ColumnStart =8
                    ColumnEnd =8
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =7356
                    Width =1008
                    FontSize =9
                    TabIndex =4
                    Name ="SentDate"
                    ControlSource ="InvoiceSentDate"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7356
                    LayoutCachedWidth =8364
                    LayoutCachedHeight =240
                    RowStart =2
                    RowEnd =2
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =3816
                    Width =3540
                    FontSize =9
                    TabIndex =3
                    Name ="UnitDesc"
                    ControlSource ="UnitDesc"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =3816
                    LayoutCachedWidth =7356
                    LayoutCachedHeight =240
                    RowStart =2
                    RowEnd =2
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =3
                    IMESentenceMode =3
                    Left =11256
                    Width =1008
                    FontSize =9
                    TabIndex =9
                    Name ="PaidDate"
                    ControlSource ="InvoicePaidDate"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =11256
                    LayoutCachedWidth =12264
                    LayoutCachedHeight =240
                    RowStart =2
                    RowEnd =2
                    ColumnStart =9
                    ColumnEnd =9
                    LayoutGroup =1
                    GroupTable =17
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =3
                    IMESentenceMode =3
                    Left =8364
                    Width =1080
                    FontSize =9
                    TabIndex =5
                    Name ="TargetSale"
                    ControlSource ="TargetSale"
                    Format ="$#,##0.00;($#,##0.00)"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =8364
                    LayoutCachedWidth =9444
                    LayoutCachedHeight =240
                    RowStart =2
                    RowEnd =2
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    GroupTable =17
                    CurrencySymbol ="$"
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =2
                    IMESentenceMode =3
                    Left =708
                    Width =1068
                    FontSize =9
                    FontWeight =700
                    TabIndex =1
                    Name ="UnitNum"
                    ControlSource ="UnitUnitNum"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =708
                    LayoutCachedWidth =1776
                    LayoutCachedHeight =240
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    ForeThemeColorIndex =4
                    ForeTint =100.0
                    ForeShade =75.0
                    GroupTable =17
                End
                Begin CommandButton
                    OverlapFlags =93
                    TextFontCharSet =2
                    TextFontFamily =2
                    Left =13032
                    Width =360
                    Height =240
                    FontSize =10
                    TabIndex =11
                    ForeColor =1643706
                    Name ="DeleteMe"
                    Caption ="Õ"
                    OnClick ="[Event Procedure]"
                    FontName ="Wingdings"
                    ControlTipText ="Remove This Unit from Buyer's Order"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =13032
                    LayoutCachedWidth =13392
                    LayoutCachedHeight =240
                    RowStart =2
                    RowEnd =2
                    ColumnStart =11
                    ColumnEnd =11
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    Shape =0
                    Gradient =0
                    BackColor =16777215
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    OldBorderStyle =0
                    BorderThemeColorIndex =1
                    BorderTint =100.0
                    ThemeFontIndex =-1
                    HoverColor =1643706
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedThemeColorIndex =9
                    HoverForeColor =16777215
                    HoverForeThemeColorIndex =-1
                    HoverForeTint =100.0
                    PressedForeColor =1643706
                    PressedForeThemeColorIndex =-1
                    PressedForeTint =100.0
                    GroupTable =17
                    QuickStyle =31
                    QuickStyleMask =-885
                    Overlaps =1
                End
                Begin TextBox
                    OverlapFlags =87
                    TextAlign =3
                    IMESentenceMode =3
                    Left =12276
                    Width =756
                    FontSize =9
                    TabIndex =10
                    Name ="Text423"
                    ControlSource ="WarrantyPrice"
                    Format ="$#,##0.00;($#,##0.00)"
                    GroupTable =17
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =12276
                    LayoutCachedWidth =13032
                    LayoutCachedHeight =240
                    RowStart =2
                    RowEnd =2
                    ColumnStart =10
                    ColumnEnd =10
                    LayoutGroup =1
                    BorderThemeColorIndex =6
                    BorderShade =50.0
                    GroupTable =17
                    CurrencySymbol ="$"
                End
            End
        End
        Begin FormFooter
            Height =0
            Name ="FormFooter"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
        End
    End
End
CodeBehindForm
' See "BuyersOrderUnits_Sub.cls"
