Version =20
VersionRequired =20
Begin Form
    RecordSelectors = NotDefault
    DividingLines = NotDefault
    AllowAdditions = NotDefault
    AllowDesignChanges = NotDefault
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridX =24
    GridY =24
    Width =20880
    DatasheetFontHeight =11
    ItemSuffix =511
    Left =-7305
    Top =1635
    Right =13590
    Bottom =13740
    RecSrcDt = Begin
        0x3f1e49038cd0e540
    End
    OnCurrent ="[Event Procedure]"
    DatasheetFontName ="Calibri"
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
    Begin
        Begin Label
            BackStyle =0
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin CommandButton
            FontSize =11
            FontWeight =400
            FontName ="Calibri"
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            UseTheme =1
            Shape =1
            Gradient =12
            BackThemeColorIndex =4
            BackTint =60.0
            BorderLineStyle =0
            BorderThemeColorIndex =4
            BorderTint =60.0
            ThemeFontIndex =1
            HoverThemeColorIndex =4
            HoverTint =40.0
            PressedThemeColorIndex =4
            PressedShade =75.0
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
        End
        Begin TextBox
            AddColon = NotDefault
            FELineBreak = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            FontName ="Calibri"
            AsianLineBreak =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin EmptyCell
            Height =240
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin FormHeader
            Height =540
            BackColor =15527148
            Name ="FormHeader"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            Begin
                Begin Label
                    Visible = NotDefault
                    OverlapFlags =85
                    TextAlign =1
                    Left =30
                    Top =30
                    Width =0
                    Height =510
                    Name ="Label0"
                    Caption ="LeaseOptionID"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =30
                    LayoutCachedTop =30
                    LayoutCachedWidth =30
                    LayoutCachedHeight =540
                    RowEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =90
                    Top =300
                    Width =870
                    Height =240
                    FontSize =9
                    ForeColor =8210719
                    Name ="Label1"
                    Caption ="AssetID"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =90
                    LayoutCachedTop =300
                    LayoutCachedWidth =960
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =1020
                    Top =300
                    Width =870
                    Height =240
                    FontSize =9
                    ForeColor =8210719
                    Name ="Label28"
                    Caption ="Unit#"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =1020
                    LayoutCachedTop =300
                    LayoutCachedWidth =1890
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    Visible = NotDefault
                    OverlapFlags =85
                    TextAlign =1
                    Left =3030
                    Top =300
                    Width =15
                    Height =240
                    FontSize =9
                    ForeColor =8210719
                    Name ="Label2"
                    Caption ="OptionTypeID"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =3030
                    LayoutCachedTop =300
                    LayoutCachedWidth =3045
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =1950
                    Top =300
                    Width =1050
                    Height =240
                    FontSize =9
                    FontWeight =700
                    ForeColor =8210719
                    Name ="Label3"
                    Caption ="Desc"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =1950
                    LayoutCachedTop =300
                    LayoutCachedWidth =3000
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =8205
                    Top =300
                    Width =510
                    Height =240
                    FontSize =9
                    ForeColor =8210719
                    Name ="Label7"
                    Caption ="Mths"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8205
                    LayoutCachedTop =300
                    LayoutCachedWidth =8715
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =9
                    ColumnEnd =9
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =9810
                    Top =300
                    Width =1005
                    Height =240
                    FontSize =9
                    ForeColor =8210719
                    Name ="Label8"
                    Caption ="Rent"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =9810
                    LayoutCachedTop =300
                    LayoutCachedWidth =10815
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =11
                    ColumnEnd =11
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =10845
                    Top =300
                    Width =825
                    Height =240
                    FontSize =9
                    ForeColor =8210719
                    Name ="Label9"
                    Caption ="Serv Fees"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10845
                    LayoutCachedTop =300
                    LayoutCachedWidth =11670
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =12
                    ColumnEnd =12
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =14925
                    Top =300
                    Width =945
                    Height =240
                    FontSize =9
                    ForeColor =8210719
                    Name ="Label10"
                    Caption ="Residual"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =14925
                    LayoutCachedTop =300
                    LayoutCachedWidth =15870
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =17
                    ColumnEnd =17
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    BackStyle =1
                    OverlapFlags =85
                    TextAlign =2
                    Left =11700
                    Top =300
                    Width =975
                    Height =240
                    FontSize =9
                    BackColor =14277081
                    ForeColor =8210719
                    Name ="Label14"
                    Caption ="Date"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =11700
                    LayoutCachedTop =300
                    LayoutCachedWidth =12675
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =13
                    ColumnEnd =13
                    LayoutGroup =1
                    BackShade =85.0
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    BackStyle =1
                    OverlapFlags =85
                    TextAlign =2
                    Left =13140
                    Top =300
                    Width =1095
                    Height =240
                    FontSize =9
                    BackColor =14277081
                    ForeColor =8210719
                    Name ="Label15"
                    Caption ="Early Penalty"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =13140
                    LayoutCachedTop =300
                    LayoutCachedWidth =14235
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =15
                    ColumnEnd =15
                    LayoutGroup =1
                    BackShade =85.0
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    BackStyle =1
                    OverlapFlags =85
                    TextAlign =1
                    Left =3045
                    Top =30
                    Width =4065
                    Height =270
                    FontSize =9
                    BackColor =14277081
                    ForeColor =8210719
                    Name ="Label16"
                    Caption ="           ┌───────── ExchangeIT ───────┐"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =3045
                    LayoutCachedTop =30
                    LayoutCachedWidth =7110
                    LayoutCachedHeight =300
                    ColumnStart =5
                    ColumnEnd =7
                    LayoutGroup =1
                    BackShade =85.0
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    BackStyle =1
                    OverlapFlags =85
                    TextAlign =2
                    Left =14235
                    Top =300
                    Width =660
                    Height =240
                    FontSize =9
                    BackColor =14277081
                    ForeColor =8210719
                    Name ="Label24"
                    Caption ="Early"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =14235
                    LayoutCachedTop =300
                    LayoutCachedWidth =14895
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =16
                    ColumnEnd =16
                    LayoutGroup =1
                    BackShade =85.0
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =15900
                    Top =300
                    Width =1485
                    Height =240
                    FontSize =9
                    ForeColor =0
                    Name ="Label25"
                    Caption ="User"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =15900
                    LayoutCachedTop =300
                    LayoutCachedWidth =17385
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =18
                    ColumnEnd =18
                    LayoutGroup =1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =17385
                    Top =300
                    Width =1920
                    Height =240
                    FontSize =9
                    ForeColor =0
                    Name ="Label26"
                    Caption ="Date"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =17385
                    LayoutCachedTop =300
                    LayoutCachedWidth =19305
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =19
                    ColumnEnd =19
                    LayoutGroup =1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    BackStyle =1
                    OverlapFlags =85
                    TextAlign =2
                    Left =4770
                    Top =300
                    Width =2340
                    Height =240
                    FontSize =9
                    BackColor =14277081
                    ForeColor =8210719
                    Name ="Label393"
                    Caption ="Sch|Grp|Unit"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =4770
                    LayoutCachedTop =300
                    LayoutCachedWidth =7110
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    BackShade =85.0
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =7110
                    Top =30
                    Width =4560
                    Height =270
                    FontSize =9
                    ForeColor =8210719
                    Name ="Label403"
                    Caption ="            ┌─────────────── ExtendIT ───────────────┐"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =7110
                    LayoutCachedTop =30
                    LayoutCachedWidth =11670
                    LayoutCachedHeight =300
                    ColumnStart =8
                    ColumnEnd =12
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =1950
                    Top =30
                    Width =1050
                    Height =270
                    Name ="EmptyCell409"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =1950
                    LayoutCachedTop =30
                    LayoutCachedWidth =3000
                    LayoutCachedHeight =300
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =90
                    Top =30
                    Width =870
                    Height =270
                    Name ="EmptyCell412"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =90
                    LayoutCachedTop =30
                    LayoutCachedWidth =960
                    LayoutCachedHeight =300
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =1020
                    Top =30
                    Width =870
                    Height =270
                    Name ="EmptyCell413"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =1020
                    LayoutCachedTop =30
                    LayoutCachedWidth =1890
                    LayoutCachedHeight =300
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin Label
                    BackStyle =1
                    OverlapFlags =85
                    TextAlign =1
                    Left =11700
                    Top =30
                    Width =3195
                    Height =270
                    FontSize =9
                    BackColor =14277081
                    ForeColor =8210719
                    Name ="Label422"
                    Caption ="          ┌──────── Terminate ────────┐"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =11700
                    LayoutCachedTop =30
                    LayoutCachedWidth =14895
                    LayoutCachedHeight =300
                    ColumnStart =13
                    ColumnEnd =16
                    LayoutGroup =1
                    BackShade =85.0
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =7110
                    Top =300
                    Width =1095
                    Height =240
                    FontSize =9
                    ForeColor =8210719
                    Name ="Label435"
                    Caption ="Start"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =7110
                    LayoutCachedTop =300
                    LayoutCachedWidth =8205
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =8
                    ColumnEnd =8
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =8715
                    Top =300
                    Width =1095
                    Height =240
                    FontSize =9
                    ForeColor =8210719
                    Name ="Label437"
                    Caption ="End"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =8715
                    LayoutCachedTop =300
                    LayoutCachedWidth =9810
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =10
                    ColumnEnd =10
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    BackStyle =1
                    OverlapFlags =85
                    TextAlign =2
                    Left =3045
                    Top =300
                    Width =1140
                    Height =240
                    FontSize =9
                    BackColor =14277081
                    ForeColor =8210719
                    Name ="Label451"
                    Caption ="Date"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =3045
                    LayoutCachedTop =300
                    LayoutCachedWidth =4185
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    BackShade =85.0
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin Label
                    BackStyle =1
                    OverlapFlags =85
                    TextAlign =2
                    Left =4185
                    Top =300
                    Width =585
                    Height =240
                    FontSize =9
                    BackColor =14277081
                    ForeColor =8210719
                    Name ="Label459"
                    Caption ="Status"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =4185
                    LayoutCachedTop =300
                    LayoutCachedWidth =4770
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackShade =85.0
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =3030
                    Top =30
                    Width =15
                    Height =270
                    Name ="EmptyCell466"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =3030
                    LayoutCachedTop =30
                    LayoutCachedWidth =3045
                    LayoutCachedHeight =300
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin Label
                    BackStyle =1
                    OverlapFlags =85
                    TextAlign =2
                    Left =12675
                    Top =300
                    Width =465
                    Height =240
                    FontSize =9
                    BackColor =14277081
                    ForeColor =8210719
                    Name ="Label474"
                    Caption ="Ind"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =12675
                    LayoutCachedTop =300
                    LayoutCachedWidth =13140
                    LayoutCachedHeight =540
                    RowStart =1
                    RowEnd =1
                    ColumnStart =14
                    ColumnEnd =14
                    LayoutGroup =1
                    BackShade =85.0
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =14925
                    Top =30
                    Width =945
                    Height =270
                    Name ="EmptyCell480"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =14925
                    LayoutCachedTop =30
                    LayoutCachedWidth =15870
                    LayoutCachedHeight =300
                    ColumnStart =17
                    ColumnEnd =17
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =2
                    Left =15900
                    Top =30
                    Width =3405
                    Height =270
                    FontSize =9
                    ForeColor =0
                    Name ="Label492"
                    Caption ="┌────────── Last Modified ─────────┐"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =15900
                    LayoutCachedTop =30
                    LayoutCachedWidth =19305
                    LayoutCachedHeight =300
                    ColumnStart =18
                    ColumnEnd =19
                    LayoutGroup =1
                    ForeTint =100.0
                    GroupTable =2
                End
            End
        End
        Begin Section
            Height =333
            Name ="Detail"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
            Begin
                Begin TextBox
                    Locked = NotDefault
                    FontUnderline = NotDefault
                    OverlapFlags =85
                    TextAlign =2
                    IMESentenceMode =3
                    Left =90
                    Top =15
                    Width =870
                    ColumnOrder =1
                    FontSize =9
                    TabIndex =2
                    Name ="UnitID"
                    ControlSource ="UnitID"
                    OnDblClick ="[Event Procedure]"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =90
                    LayoutCachedTop =15
                    LayoutCachedWidth =960
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Visible = NotDefault
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =30
                    Top =15
                    Width =0
                    ColumnOrder =0
                    TabIndex =1
                    Name ="LeaseOptionID"
                    ControlSource ="LeaseOptionID"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =30
                    LayoutCachedTop =15
                    LayoutCachedWidth =30
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Visible = NotDefault
                    OverlapFlags =93
                    TextAlign =1
                    IMESentenceMode =3
                    Left =3030
                    Top =15
                    Width =15
                    ColumnOrder =2
                    FontSize =9
                    TabIndex =5
                    Name ="OptionTypeID"
                    ControlSource ="OptionTypeID"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =3030
                    LayoutCachedTop =15
                    LayoutCachedWidth =3045
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =1950
                    Top =15
                    Width =1050
                    ColumnOrder =5
                    FontSize =9
                    FontWeight =700
                    TabIndex =4
                    ForeColor =0
                    Name ="OptionTypeDesc"
                    ControlSource ="OptionTypeDesc"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =1950
                    LayoutCachedTop =15
                    LayoutCachedWidth =3000
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =7110
                    Top =15
                    Width =1095
                    ColumnOrder =3
                    FontSize =9
                    TabIndex =9
                    Name ="StartOrPurposedDate"
                    ControlSource ="ExtendITStartDate"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7110
                    LayoutCachedTop =15
                    LayoutCachedWidth =8205
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =8
                    ColumnEnd =8
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =3
                    IMESentenceMode =3
                    Left =8715
                    Top =15
                    Width =1095
                    ColumnOrder =4
                    FontSize =9
                    TabIndex =11
                    Name ="EndOrActualDate"
                    ControlSource ="ExtendITEndDate"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =8715
                    LayoutCachedTop =15
                    LayoutCachedWidth =9810
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =10
                    ColumnEnd =10
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =2
                    IMESentenceMode =3
                    Left =8205
                    Top =15
                    Width =510
                    FontSize =9
                    TabIndex =10
                    Name ="TermMonths"
                    ControlSource ="TermMonths"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =8205
                    LayoutCachedTop =15
                    LayoutCachedWidth =8715
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =9
                    ColumnEnd =9
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =3
                    IMESentenceMode =3
                    Left =9810
                    Top =15
                    Width =1005
                    FontSize =9
                    TabIndex =12
                    Name ="Rent"
                    ControlSource ="ExtendedRent"
                    Format ="$#,##0.00;($#,##0.00)"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =9810
                    LayoutCachedTop =15
                    LayoutCachedWidth =10815
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =11
                    ColumnEnd =11
                    LayoutGroup =1
                    GroupTable =2
                    CurrencySymbol ="$"
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =3
                    IMESentenceMode =3
                    Left =10845
                    Top =15
                    Width =825
                    FontSize =9
                    TabIndex =13
                    Name ="Fees"
                    ControlSource ="ExtendedFees"
                    Format ="$#,##0.00;($#,##0.00)"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =10845
                    LayoutCachedTop =15
                    LayoutCachedWidth =11670
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =12
                    ColumnEnd =12
                    LayoutGroup =1
                    GroupTable =2
                    CurrencySymbol ="$"
                End
                Begin TextBox
                    Locked = NotDefault
                    DecimalPlaces =0
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =3
                    IMESentenceMode =3
                    Left =14925
                    Top =15
                    Width =945
                    FontSize =9
                    TabIndex =18
                    Name ="Residual"
                    ControlSource ="Residual"
                    Format ="$#,##0.00;($#,##0.00)"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =14925
                    LayoutCachedTop =15
                    LayoutCachedWidth =15870
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =17
                    ColumnEnd =17
                    LayoutGroup =1
                    GroupTable =2
                    CurrencySymbol ="$"
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =3
                    IMESentenceMode =3
                    Left =11700
                    Top =15
                    Width =975
                    FontSize =9
                    TabIndex =14
                    Name ="TerminateDate"
                    ControlSource ="TermDate"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =11700
                    LayoutCachedTop =15
                    LayoutCachedWidth =12675
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =13
                    ColumnEnd =13
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =3
                    IMESentenceMode =3
                    Left =13140
                    Top =15
                    Width =1095
                    FontSize =9
                    TabIndex =16
                    Name ="TerminateFeeCol"
                    ControlSource ="GainLoss"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =13140
                    LayoutCachedTop =15
                    LayoutCachedWidth =14235
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =15
                    ColumnEnd =15
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =2
                    IMESentenceMode =3
                    Left =4770
                    Top =15
                    Width =2340
                    FontSize =9
                    TabIndex =8
                    Name ="FinalPaymntAmt"
                    ControlSource ="ExchangeITSchGrpUnit"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4770
                    LayoutCachedTop =15
                    LayoutCachedWidth =7110
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =2
                    IMESentenceMode =3
                    Left =14235
                    Top =15
                    Width =660
                    ColumnWidth =2190
                    FontSize =9
                    TabIndex =17
                    Name ="TerminateEarlyCol"
                    ControlSource ="TermEarly"
                    Format ="Yes/No"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =14235
                    LayoutCachedTop =15
                    LayoutCachedWidth =14895
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =16
                    ColumnEnd =16
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =15900
                    Top =15
                    Width =1485
                    FontSize =8
                    TabIndex =19
                    Name ="UserName"
                    ControlSource ="UserName"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =15900
                    LayoutCachedTop =15
                    LayoutCachedWidth =17385
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =18
                    ColumnEnd =18
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    FontItalic = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =3
                    IMESentenceMode =3
                    Left =17385
                    Top =15
                    Width =1920
                    FontSize =8
                    TabIndex =20
                    Name ="DatePosted"
                    ControlSource ="DatePosted"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =17385
                    LayoutCachedTop =15
                    LayoutCachedWidth =19305
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =19
                    ColumnEnd =19
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =2
                    IMESentenceMode =3
                    Left =1020
                    Top =15
                    Width =870
                    ColumnOrder =6
                    FontSize =9
                    TabIndex =3
                    Name ="UnitUnitNum"
                    ControlSource ="UnitUnitNum"
                    StatusBarText ="Text/Number the Customer uses to ID the Unit"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =1020
                    LayoutCachedTop =15
                    LayoutCachedWidth =1890
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Top =274
                    Width =19440
                    Height =59
                    TabIndex =21
                    BorderColor =12632256
                    ForeColor =16777215
                    Name ="Marker"
                    ConditionalFormat = Begin
                        0x010000008e000000010000000100000000000000000000001600000001000000 ,
                        0xffffff001f497d00000000000000000000000000000000000000000000000000 ,
                        0x0000000000000000000000000000000000000000000000000000000000000000 ,
                        0x5b0055006e0069007400490044005d003d005b00740078007400430075007200 ,
                        0x720065006e0074005d0000000000
                    End
                    GridlineColor =0

                    LayoutCachedTop =274
                    LayoutCachedWidth =19440
                    LayoutCachedHeight =333
                    BackThemeColorIndex =-1
                    BorderThemeColorIndex =-1
                    BorderShade =100.0
                    ThemeFontIndex =-1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    ConditionalFormat14 = Begin
                        0x010001000000010000000000000001000000ffffff001f497d00150000005b00 ,
                        0x55006e0069007400490044005d003d005b007400780074004300750072007200 ,
                        0x65006e0074005d00000000000000000000000000000000000000000000
                    End
                    GridlineThemeColorIndex =-1
                    GridlineShade =100.0
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =87
                    TextAlign =2
                    IMESentenceMode =3
                    Left =3045
                    Top =15
                    Width =1140
                    FontSize =9
                    TabIndex =6
                    Name ="Text442"
                    ControlSource ="ExchangeITDate"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =3045
                    LayoutCachedTop =15
                    LayoutCachedWidth =4185
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =2
                    IMESentenceMode =3
                    Left =4185
                    Top =15
                    Width =585
                    FontSize =9
                    TabIndex =7
                    Name ="ExchangeITStatus"
                    ControlSource ="ExchangeITStatus"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4185
                    LayoutCachedTop =15
                    LayoutCachedWidth =4770
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    OldBorderStyle =0
                    OverlapFlags =85
                    TextAlign =1
                    IMESentenceMode =3
                    Left =12675
                    Top =15
                    Width =465
                    FontSize =8
                    FontWeight =700
                    TabIndex =15
                    Name ="TermStatus"
                    ControlSource ="TermStatus"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =12675
                    LayoutCachedTop =15
                    LayoutCachedWidth =13140
                    LayoutCachedHeight =255
                    RowStart =2
                    RowEnd =2
                    ColumnStart =14
                    ColumnEnd =14
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin CommandButton
                    OverlapFlags =85
                    TextFontCharSet =2
                    TextFontFamily =2
                    Left =19485
                    Top =15
                    Width =330
                    Height =302
                    FontSize =10
                    ForeColor =1643706
                    Name ="DeleteMe"
                    Caption ="Õ"
                    OnClick ="[Event Procedure]"
                    FontName ="Wingdings"
                    ControlTipText ="Delete This Unit's Option"
                    TopPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =19485
                    LayoutCachedTop =15
                    LayoutCachedWidth =19815
                    LayoutCachedHeight =317
                    RowStart =2
                    RowEnd =2
                    ColumnStart =20
                    ColumnEnd =20
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    Shape =0
                    Gradient =0
                    BackColor =15527148
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    OldBorderStyle =0
                    BorderThemeColorIndex =1
                    BorderTint =100.0
                    ThemeFontIndex =-1
                    HoverColor =1643706
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =15527148
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeColor =16777215
                    HoverForeThemeColorIndex =-1
                    HoverForeTint =100.0
                    PressedForeColor =1643706
                    PressedForeThemeColorIndex =-1
                    PressedForeTint =100.0
                    QuickStyle =31
                    QuickStyleMask =-885
                End
            End
        End
        Begin FormFooter
            Height =270
            Name ="FormFooter"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
            Begin
                Begin TextBox
                    Visible = NotDefault
                    OverlapFlags =93
                    TextAlign =2
                    IMESentenceMode =3
                    Width =29
                    Height =270
                    FontWeight =700
                    BorderColor =12632256
                    ForeColor =0
                    Name ="UnitCount"
                    ControlSource ="=Count([UnitID])"
                    GridlineColor =0

                    LayoutCachedWidth =29
                    LayoutCachedHeight =270
                    BackThemeColorIndex =2
                    BorderThemeColorIndex =-1
                    BorderShade =100.0
                    ThemeFontIndex =-1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GridlineThemeColorIndex =-1
                    GridlineShade =100.0
                End
                Begin TextBox
                    Visible = NotDefault
                    OverlapFlags =247
                    IMESentenceMode =3
                    Width =765
                    Height =210
                    FontSize =8
                    TabIndex =1
                    BorderColor =12632256
                    ForeColor =0
                    Name ="txtCurrent"
                    GridlineColor =0

                    LayoutCachedWidth =765
                    LayoutCachedHeight =210
                    BackThemeColorIndex =-1
                    BorderThemeColorIndex =-1
                    BorderShade =100.0
                    ThemeFontIndex =-1
                    ForeThemeColorIndex =-1
                    ForeTint =100.0
                    GridlineThemeColorIndex =-1
                    GridlineShade =100.0
                End
            End
        End
    End
End
CodeBehindForm
' See "ExitOptions_subform_History.cls"
