Version =20
VersionRequired =20
Begin Form
    AutoResize = NotDefault
    PopUp = NotDefault
    RecordSelectors = NotDefault
    AutoCenter = NotDefault
    DividingLines = NotDefault
    AllowDesignChanges = NotDefault
    TabularCharSet =238
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridX =24
    GridY =24
    Width =19635
    DatasheetFontHeight =11
    ItemSuffix =55
    Left =4845
    Top =4440
    Right =19470
    Bottom =9945
    ShortcutMenuBar ="SortClip"
    RecSrcDt = Begin
        0xf73215139279e440
    End
    DatasheetFontName ="Calibri"
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =16053492
    DatasheetGridlinesColor12 =15062992
    FitToScreen =1
    Begin
        Begin Label
            BackStyle =0
            FontSize =11
            FontName ="Calibri"
        End
        Begin Rectangle
            SpecialEffect =3
            BackStyle =0
            BorderLineStyle =0
        End
        Begin CommandButton
            FontSize =11
            FontWeight =400
            ForeColor =-2147483630
            FontName ="Calibri"
            BorderLineStyle =0
        End
        Begin TextBox
            FELineBreak = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            BorderColor =12632256
            FontName ="Calibri"
            AsianLineBreak =1
        End
        Begin ListBox
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            BorderColor =12632256
            FontName ="Calibri"
            AllowValueListEdits =1
            InheritValueList =1
        End
        Begin ComboBox
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            BorderColor =12632256
            FontName ="Calibri"
            AllowValueListEdits =1
            InheritValueList =1
        End
        Begin FormHeader
            Height =372
            Name ="FormHeader"
            Begin
                Begin Rectangle
                    SpecialEffect =0
                    BackStyle =1
                    OverlapFlags =93
                    Left =30
                    Width =19605
                    Height =330
                    BackColor =26112
                    BorderColor =10855845
                    Name ="Box22"
                    HorizontalAnchor =2
                    LayoutCachedLeft =30
                    LayoutCachedWidth =19635
                    LayoutCachedHeight =330
                End
                Begin Label
                    OverlapFlags =215
                    Left =9084
                    Top =36
                    Width =2016
                    Height =312
                    ForeColor =16777215
                    Name ="Label6"
                    Caption ="UnitVIN:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =9084
                    LayoutCachedTop =36
                    LayoutCachedWidth =11100
                    LayoutCachedHeight =348
                    ColumnStart =11
                    ColumnEnd =11
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =1116
                    Top =36
                    Width =732
                    Height =312
                    ForeColor =16777215
                    Name ="Label7"
                    Caption ="Asset:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =1116
                    LayoutCachedTop =36
                    LayoutCachedWidth =1848
                    LayoutCachedHeight =348
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =2772
                    Top =36
                    Width =540
                    Height =312
                    ForeColor =16777215
                    Name ="Label8"
                    Caption ="Year:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =2772
                    LayoutCachedTop =36
                    LayoutCachedWidth =3312
                    LayoutCachedHeight =348
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =3384
                    Top =36
                    Width =1440
                    Height =312
                    ForeColor =16777215
                    Name ="Label9"
                    Caption ="Make:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =3384
                    LayoutCachedTop =36
                    LayoutCachedWidth =4824
                    LayoutCachedHeight =348
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =4896
                    Top =36
                    Width =1728
                    Height =312
                    ForeColor =16777215
                    Name ="Label10"
                    Caption ="Model:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =4896
                    LayoutCachedTop =36
                    LayoutCachedWidth =6624
                    LayoutCachedHeight =348
                    ColumnStart =8
                    ColumnEnd =8
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =6696
                    Top =36
                    Width =1812
                    Height =312
                    ForeColor =16777215
                    Name ="Label11"
                    Caption ="Type:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =6696
                    LayoutCachedTop =36
                    LayoutCachedWidth =8508
                    LayoutCachedHeight =348
                    ColumnStart =9
                    ColumnEnd =9
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    TextAlign =2
                    Left =1920
                    Top =36
                    Width =780
                    Height =312
                    ForeColor =16777215
                    Name ="Label12"
                    Caption ="Est'Dt"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =1920
                    LayoutCachedTop =36
                    LayoutCachedWidth =2700
                    LayoutCachedHeight =348
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =85
                    Left =36
                    Top =36
                    Width =0
                    Height =312
                    ForeColor =16777215
                    Name ="Label16"
                    Caption ="FAID"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =36
                    LayoutCachedTop =36
                    LayoutCachedWidth =36
                    LayoutCachedHeight =348
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    TextAlign =1
                    Left =252
                    Top =36
                    Width =792
                    Height =312
                    ForeColor =16777215
                    Name ="Label19"
                    Caption ="UnitID:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =252
                    LayoutCachedTop =36
                    LayoutCachedWidth =1044
                    LayoutCachedHeight =348
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =11172
                    Top =36
                    Width =1716
                    Height =312
                    ForeColor =16777215
                    Name ="Label36"
                    Caption ="REFENG"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =11172
                    LayoutCachedTop =36
                    LayoutCachedWidth =12888
                    LayoutCachedHeight =348
                    ColumnStart =12
                    ColumnEnd =12
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =12960
                    Top =36
                    Width =1752
                    Height =312
                    ForeColor =16777215
                    Name ="Label38"
                    Caption ="COMPRESSS"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =12960
                    LayoutCachedTop =36
                    LayoutCachedWidth =14712
                    LayoutCachedHeight =348
                    ColumnStart =13
                    ColumnEnd =13
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =85
                    Left =180
                    Top =36
                    Width =0
                    Height =312
                    ForeColor =16777215
                    Name ="VendorNameLBL"
                    Caption ="VendorName"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =180
                    LayoutCachedTop =36
                    LayoutCachedWidth =180
                    LayoutCachedHeight =348
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =14784
                    Top =36
                    Width =1668
                    Height =312
                    ForeColor =16777215
                    Name ="Label42"
                    Caption ="MICROPROC"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =14784
                    LayoutCachedTop =36
                    LayoutCachedWidth =16452
                    LayoutCachedHeight =348
                    ColumnStart =14
                    ColumnEnd =14
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =16524
                    Top =36
                    Width =1668
                    Height =312
                    ForeColor =16777215
                    Name ="Label46"
                    Caption ="ELECDISP"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =16524
                    LayoutCachedTop =36
                    LayoutCachedWidth =18192
                    LayoutCachedHeight =348
                    ColumnStart =15
                    ColumnEnd =15
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    TextAlign =2
                    Left =8580
                    Top =36
                    Width =432
                    Height =312
                    ForeColor =16777215
                    Name ="Label52"
                    Caption ="STS"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =8580
                    LayoutCachedTop =36
                    LayoutCachedWidth =9012
                    LayoutCachedHeight =348
                    ColumnStart =10
                    ColumnEnd =10
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =85
                    Left =108
                    Top =36
                    Width =0
                    Height =312
                    ForeColor =16777215
                    Name ="VendorIDLBL"
                    Caption ="VendorID"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =108
                    LayoutCachedTop =36
                    LayoutCachedWidth =108
                    LayoutCachedHeight =348
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                End
            End
        End
        Begin Section
            Height =350
            Name ="Detail"
            AlternateBackColor =15858167
            Begin
                Begin TextBox
                    OverlapFlags =85
                    TextFontFamily =50
                    IMESentenceMode =3
                    Left =9084
                    Top =36
                    Width =2016
                    Height =276
                    ColumnWidth =2805
                    FontSize =9
                    TabIndex =11
                    Name ="VIN"
                    ControlSource ="ChildVIN"
                    FontName ="OCR A Extended"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =9084
                    LayoutCachedTop =36
                    LayoutCachedWidth =11100
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =11
                    ColumnEnd =11
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =1116
                    Top =36
                    Width =732
                    Height =276
                    ColumnWidth =1125
                    FontSize =9
                    TabIndex =3
                    Name ="AssetID"
                    ControlSource ="Asset"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =1116
                    LayoutCachedTop =36
                    LayoutCachedWidth =1848
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =2772
                    Top =36
                    Width =540
                    Height =276
                    FontSize =9
                    TabIndex =6
                    Name ="UnitYr"
                    ControlSource ="ChildYear"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =2772
                    LayoutCachedTop =36
                    LayoutCachedWidth =3312
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =3384
                    Top =36
                    Height =276
                    FontSize =9
                    TabIndex =7
                    Name ="UnitMake"
                    ControlSource ="ChildMake"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =3384
                    LayoutCachedTop =36
                    LayoutCachedWidth =4824
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =4896
                    Top =36
                    Width =1728
                    Height =276
                    FontSize =9
                    TabIndex =8
                    Name ="UnitModel"
                    ControlSource ="ChildClass"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =4896
                    LayoutCachedTop =36
                    LayoutCachedWidth =6624
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =8
                    ColumnEnd =8
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =6696
                    Top =36
                    Width =1812
                    Height =276
                    ColumnWidth =2910
                    FontSize =9
                    TabIndex =9
                    Name ="UnitType"
                    ControlSource ="ChildType"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =6696
                    LayoutCachedTop =36
                    LayoutCachedWidth =8508
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =9
                    ColumnEnd =9
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =1920
                    Top =36
                    Width =780
                    Height =276
                    ColumnWidth =1755
                    FontSize =9
                    TabIndex =5
                    Name ="UnitEstDelDate"
                    ControlSource ="EstDelDate"
                    Format ="mm/dd/yy"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =1920
                    LayoutCachedTop =36
                    LayoutCachedWidth =2700
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =36
                    Top =36
                    Width =0
                    Height =276
                    ColumnWidth =2145
                    FontSize =9
                    Name ="ChildFAID"
                    ControlSource ="SGrpFAID"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =36
                    LayoutCachedTop =36
                    LayoutCachedWidth =36
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    TextAlign =2
                    IMESentenceMode =3
                    Left =252
                    Top =36
                    Width =792
                    Height =276
                    ColumnWidth =2145
                    FontSize =9
                    TabIndex =4
                    Name ="ChildPartID"
                    ControlSource ="ChildPartID"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =252
                    LayoutCachedTop =36
                    LayoutCachedWidth =1044
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontFamily =50
                    IMESentenceMode =3
                    Left =11172
                    Top =36
                    Width =1716
                    Height =276
                    FontSize =9
                    TabIndex =12
                    Name ="REFENG"
                    ControlSource ="REFENG"
                    FontName ="OCR A Extended"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =11172
                    LayoutCachedTop =36
                    LayoutCachedWidth =12888
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =12
                    ColumnEnd =12
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontFamily =50
                    IMESentenceMode =3
                    Left =12960
                    Top =36
                    Width =1752
                    Height =276
                    FontSize =9
                    TabIndex =13
                    Name ="COMPRESSS"
                    ControlSource ="COMPRESSS"
                    FontName ="OCR A Extended"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =12960
                    LayoutCachedTop =36
                    LayoutCachedWidth =14712
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =13
                    ColumnEnd =13
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =180
                    Top =36
                    Width =0
                    Height =276
                    FontSize =10
                    TabIndex =2
                    Name ="VendorName"
                    ControlSource ="VendorName"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =180
                    LayoutCachedTop =36
                    LayoutCachedWidth =180
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontFamily =50
                    IMESentenceMode =3
                    Left =14784
                    Top =36
                    Width =1668
                    Height =276
                    FontSize =9
                    TabIndex =14
                    Name ="MICROPROC"
                    ControlSource ="MICROPROC"
                    FontName ="OCR A Extended"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =14784
                    LayoutCachedTop =36
                    LayoutCachedWidth =16452
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =14
                    ColumnEnd =14
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontFamily =50
                    IMESentenceMode =3
                    Left =16524
                    Top =36
                    Width =1668
                    Height =276
                    FontSize =9
                    TabIndex =15
                    Name ="ELECDISP"
                    ControlSource ="ELECDISP"
                    FontName ="OCR A Extended"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =16524
                    LayoutCachedTop =36
                    LayoutCachedWidth =18192
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =15
                    ColumnEnd =15
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    TextAlign =2
                    IMESentenceMode =3
                    Left =8580
                    Top =36
                    Width =432
                    Height =276
                    FontSize =9
                    TabIndex =10
                    Name ="ChildStatus"
                    ControlSource ="ChildStatus"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =8580
                    LayoutCachedTop =36
                    LayoutCachedWidth =9012
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =10
                    ColumnEnd =10
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =108
                    Top =36
                    Width =0
                    Height =276
                    FontSize =9
                    TabIndex =1
                    Name ="VendorID"
                    ControlSource ="VendorID"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =108
                    LayoutCachedTop =36
                    LayoutCachedWidth =108
                    LayoutCachedHeight =312
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                End
            End
        End
        Begin FormFooter
            Height =0
            Name ="FormFooter"
            AutoHeight =1
        End
    End
End
CodeBehindForm
' See "Open_Items_ChildParts_SubForm.cls"
