Version =20
VersionRequired =20
Begin Form
    AutoResize = NotDefault
    PopUp = NotDefault
    RecordSelectors = NotDefault
    AutoCenter = NotDefault
    DividingLines = NotDefault
    AllowDesignChanges = NotDefault
    TabularCharSet =238
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridX =24
    GridY =24
    Width =19635
    DatasheetFontHeight =11
    ItemSuffix =55
    Left =4845
    Top =4440
    Right =19470
    Bottom =9945
    ShortcutMenuBar ="SortClip"
    RecSrcDt = Begin
        0xf73215139279e440
    End
    DatasheetFontName ="Calibri"
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =16053492
    DatasheetGridlinesColor12 =15062992
    FitToScreen =1
    Begin
        Begin Label
            BackStyle =0
            FontSize =11
            FontName ="Calibri"
        End
        Begin Rectangle
            SpecialEffect =3
            BackStyle =0
            BorderLineStyle =0
        End
        Begin CommandButton
            FontSize =11
            FontWeight =400
            ForeColor =-2147483630
            FontName ="Calibri"
            BorderLineStyle =0
        End
        Begin TextBox
            FELineBreak = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            BorderColor =12632256
            FontName ="Calibri"
            AsianLineBreak =1
        End
        Begin ListBox
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            BorderColor =12632256
            FontName ="Calibri"
            AllowValueListEdits =1
            InheritValueList =1
        End
        Begin ComboBox
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            BorderColor =12632256
            FontName ="Calibri"
            AllowValueListEdits =1
            InheritValueList =1
        End
        Begin FormHeader
            Height =367
            Name ="FormHeader"
            Begin
                Begin Rectangle
                    SpecialEffect =0
                    BackStyle =1
                    OverlapFlags =93
                    Left =30
                    Width =19605
                    Height =330
                    BackColor =26112
                    BorderColor =10855845
                    Name ="Box22"
                    HorizontalAnchor =2
                    LayoutCachedLeft =30
                    LayoutCachedWidth =19635
                    LayoutCachedHeight =330
                End
                Begin Label
                    OverlapFlags =215
                    Left =9120
                    Top =30
                    Width =2010
                    Height =315
                    ForeColor =16777215
                    Name ="Label6"
                    Caption ="UnitVIN:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =9120
                    LayoutCachedTop =30
                    LayoutCachedWidth =11130
                    LayoutCachedHeight =345
                    ColumnStart =11
                    ColumnEnd =11
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =1125
                    Top =30
                    Width =735
                    Height =315
                    ForeColor =16777215
                    Name ="Label7"
                    Caption ="Asset:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =1125
                    LayoutCachedTop =30
                    LayoutCachedWidth =1860
                    LayoutCachedHeight =345
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =2790
                    Top =30
                    Width =540
                    Height =315
                    ForeColor =16777215
                    Name ="Label8"
                    Caption ="Year:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =2790
                    LayoutCachedTop =30
                    LayoutCachedWidth =3330
                    LayoutCachedHeight =345
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =3405
                    Top =30
                    Width =1440
                    Height =315
                    ForeColor =16777215
                    Name ="Label9"
                    Caption ="Make:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =3405
                    LayoutCachedTop =30
                    LayoutCachedWidth =4845
                    LayoutCachedHeight =345
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =4920
                    Top =30
                    Width =1725
                    Height =315
                    ForeColor =16777215
                    Name ="Label10"
                    Caption ="Model:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =4920
                    LayoutCachedTop =30
                    LayoutCachedWidth =6645
                    LayoutCachedHeight =345
                    ColumnStart =8
                    ColumnEnd =8
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =6720
                    Top =30
                    Width =1815
                    Height =315
                    ForeColor =16777215
                    Name ="Label11"
                    Caption ="Type:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =6720
                    LayoutCachedTop =30
                    LayoutCachedWidth =8535
                    LayoutCachedHeight =345
                    ColumnStart =9
                    ColumnEnd =9
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    TextAlign =2
                    Left =1935
                    Top =30
                    Width =780
                    Height =315
                    ForeColor =16777215
                    Name ="Label12"
                    Caption ="Est'Dt"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =1935
                    LayoutCachedTop =30
                    LayoutCachedWidth =2715
                    LayoutCachedHeight =345
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =85
                    Left =30
                    Top =30
                    Width =0
                    Height =315
                    ForeColor =16777215
                    Name ="Label16"
                    Caption ="FAID"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =30
                    LayoutCachedTop =30
                    LayoutCachedWidth =30
                    LayoutCachedHeight =345
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    TextAlign =1
                    Left =255
                    Top =30
                    Width =795
                    Height =315
                    ForeColor =16777215
                    Name ="Label19"
                    Caption ="UnitID:"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =255
                    LayoutCachedTop =30
                    LayoutCachedWidth =1050
                    LayoutCachedHeight =345
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =11205
                    Top =30
                    Width =1710
                    Height =315
                    ForeColor =16777215
                    Name ="Label36"
                    Caption ="REFENG"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =11205
                    LayoutCachedTop =30
                    LayoutCachedWidth =12915
                    LayoutCachedHeight =345
                    ColumnStart =12
                    ColumnEnd =12
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =12990
                    Top =30
                    Width =1755
                    Height =315
                    ForeColor =16777215
                    Name ="Label38"
                    Caption ="COMPRESSS"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =12990
                    LayoutCachedTop =30
                    LayoutCachedWidth =14745
                    LayoutCachedHeight =345
                    ColumnStart =13
                    ColumnEnd =13
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =85
                    Left =180
                    Top =30
                    Width =0
                    Height =315
                    ForeColor =16777215
                    Name ="VendorNameLBL"
                    Caption ="VendorName"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =180
                    LayoutCachedTop =30
                    LayoutCachedWidth =180
                    LayoutCachedHeight =345
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =14820
                    Top =30
                    Width =1665
                    Height =315
                    ForeColor =16777215
                    Name ="Label42"
                    Caption ="MICROPROC"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =14820
                    LayoutCachedTop =30
                    LayoutCachedWidth =16485
                    LayoutCachedHeight =345
                    ColumnStart =14
                    ColumnEnd =14
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    Left =16560
                    Top =30
                    Width =1665
                    Height =315
                    ForeColor =16777215
                    Name ="Label46"
                    Caption ="ELECDISP"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =16560
                    LayoutCachedTop =30
                    LayoutCachedWidth =18225
                    LayoutCachedHeight =345
                    ColumnStart =15
                    ColumnEnd =15
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =215
                    TextAlign =2
                    Left =8610
                    Top =30
                    Width =435
                    Height =315
                    ForeColor =16777215
                    Name ="Label52"
                    Caption ="STS"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =8610
                    LayoutCachedTop =30
                    LayoutCachedWidth =9045
                    LayoutCachedHeight =345
                    ColumnStart =10
                    ColumnEnd =10
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin Label
                    OverlapFlags =85
                    Left =105
                    Top =30
                    Width =0
                    Height =315
                    ForeColor =16777215
                    Name ="VendorIDLBL"
                    Caption ="VendorID"
                    GroupTable =1
                    RightPadding =38
                    LayoutCachedLeft =105
                    LayoutCachedTop =30
                    LayoutCachedWidth =105
                    LayoutCachedHeight =345
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                End
            End
        End
        Begin Section
            Height =338
            Name ="Detail"
            AlternateBackColor =15858167
            Begin
                Begin TextBox
                    OverlapFlags =85
                    TextFontFamily =50
                    IMESentenceMode =3
                    Left =9120
                    Top =30
                    Width =2010
                    Height =270
                    ColumnWidth =2805
                    FontSize =9
                    TabIndex =11
                    Name ="VIN"
                    ControlSource ="ChildVIN"
                    FontName ="OCR A Extended"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =9120
                    LayoutCachedTop =30
                    LayoutCachedWidth =11130
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =11
                    ColumnEnd =11
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =1125
                    Top =30
                    Width =735
                    Height =270
                    ColumnWidth =1125
                    FontSize =9
                    TabIndex =3
                    Name ="AssetID"
                    ControlSource ="Asset"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =1125
                    LayoutCachedTop =30
                    LayoutCachedWidth =1860
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =2790
                    Top =30
                    Width =540
                    Height =270
                    FontSize =9
                    TabIndex =6
                    Name ="UnitYr"
                    ControlSource ="ChildYear"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =2790
                    LayoutCachedTop =30
                    LayoutCachedWidth =3330
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =3405
                    Top =30
                    Height =270
                    FontSize =9
                    TabIndex =7
                    Name ="UnitMake"
                    ControlSource ="ChildMake"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =3405
                    LayoutCachedTop =30
                    LayoutCachedWidth =4845
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =4920
                    Top =30
                    Width =1725
                    Height =270
                    FontSize =9
                    TabIndex =8
                    Name ="UnitModel"
                    ControlSource ="ChildClass"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =4920
                    LayoutCachedTop =30
                    LayoutCachedWidth =6645
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =8
                    ColumnEnd =8
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =6720
                    Top =30
                    Width =1815
                    Height =270
                    ColumnWidth =2910
                    FontSize =9
                    TabIndex =9
                    Name ="UnitType"
                    ControlSource ="ChildType"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =6720
                    LayoutCachedTop =30
                    LayoutCachedWidth =8535
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =9
                    ColumnEnd =9
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =1935
                    Top =30
                    Width =780
                    Height =270
                    ColumnWidth =1755
                    FontSize =9
                    TabIndex =5
                    Name ="UnitEstDelDate"
                    ControlSource ="EstDelDate"
                    Format ="mm/dd/yy"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =1935
                    LayoutCachedTop =30
                    LayoutCachedWidth =2715
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =30
                    Top =30
                    Width =0
                    Height =270
                    ColumnWidth =2145
                    FontSize =9
                    Name ="ChildFAID"
                    ControlSource ="SGrpFAID"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =30
                    LayoutCachedTop =30
                    LayoutCachedWidth =30
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    TextAlign =2
                    IMESentenceMode =3
                    Left =255
                    Top =30
                    Width =795
                    Height =270
                    ColumnWidth =2145
                    FontSize =9
                    TabIndex =4
                    Name ="ChildPartID"
                    ControlSource ="ChildPartID"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =255
                    LayoutCachedTop =30
                    LayoutCachedWidth =1050
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontFamily =50
                    IMESentenceMode =3
                    Left =11205
                    Top =30
                    Width =1710
                    Height =270
                    FontSize =9
                    TabIndex =12
                    Name ="REFENG"
                    ControlSource ="REFENG"
                    FontName ="OCR A Extended"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =11205
                    LayoutCachedTop =30
                    LayoutCachedWidth =12915
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =12
                    ColumnEnd =12
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontFamily =50
                    IMESentenceMode =3
                    Left =12990
                    Top =30
                    Width =1755
                    Height =270
                    FontSize =9
                    TabIndex =13
                    Name ="COMPRESSS"
                    ControlSource ="COMPRESSS"
                    FontName ="OCR A Extended"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =12990
                    LayoutCachedTop =30
                    LayoutCachedWidth =14745
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =13
                    ColumnEnd =13
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =180
                    Top =30
                    Width =0
                    Height =270
                    FontSize =10
                    TabIndex =2
                    Name ="VendorName"
                    ControlSource ="VendorName"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =180
                    LayoutCachedTop =30
                    LayoutCachedWidth =180
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontFamily =50
                    IMESentenceMode =3
                    Left =14820
                    Top =30
                    Width =1665
                    Height =270
                    FontSize =9
                    TabIndex =14
                    Name ="MICROPROC"
                    ControlSource ="MICROPROC"
                    FontName ="OCR A Extended"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =14820
                    LayoutCachedTop =30
                    LayoutCachedWidth =16485
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =14
                    ColumnEnd =14
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontFamily =50
                    IMESentenceMode =3
                    Left =16560
                    Top =30
                    Width =1665
                    Height =270
                    FontSize =9
                    TabIndex =15
                    Name ="ELECDISP"
                    ControlSource ="ELECDISP"
                    FontName ="OCR A Extended"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =16560
                    LayoutCachedTop =30
                    LayoutCachedWidth =18225
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =15
                    ColumnEnd =15
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    TextAlign =2
                    IMESentenceMode =3
                    Left =8610
                    Top =30
                    Width =435
                    Height =270
                    FontSize =9
                    TabIndex =10
                    Name ="ChildStatus"
                    ControlSource ="ChildStatus"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =8610
                    LayoutCachedTop =30
                    LayoutCachedWidth =9045
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =10
                    ColumnEnd =10
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    OverlapFlags =85
                    TextFontCharSet =238
                    IMESentenceMode =3
                    Left =105
                    Top =30
                    Width =0
                    Height =270
                    FontSize =9
                    TabIndex =1
                    Name ="VendorID"
                    ControlSource ="VendorID"
                    GroupTable =1
                    RightPadding =38
                    BottomPadding =38

                    LayoutCachedLeft =105
                    LayoutCachedTop =30
                    LayoutCachedWidth =105
                    LayoutCachedHeight =300
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                End
            End
        End
        Begin FormFooter
            Height =0
            Name ="FormFooter"
            AutoHeight =1
        End
    End
End
CodeBehindForm
' See "Open_Items_ChildParts_SubForm.cls"
