Version =20
VersionRequired =20
Begin Form
    PopUp = NotDefault
    RecordSelectors = NotDefault
    MaxButton = NotDefault
    MinButton = NotDefault
    ControlBox = NotDefault
    NavigationButtons = NotDefault
    CloseButton = NotDefault
    DividingLines = NotDefault
    AllowEdits = NotDefault
    AllowDesignChanges = NotDefault
    DefaultView =0
    ScrollBars =0
    TabularCharSet =163
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridX =24
    GridY =24
    Width =11580
    DatasheetFontHeight =11
    ItemSuffix =291
    Left =5235
    Top =13800
    Right =16215
    Bottom =17400
    ShortcutMenuBar ="SortClip"
    RecSrcDt = Begin
        0x35d4eddad297e540
    End
    OnClose ="[Event Procedure]"
    DatasheetFontName ="Calibri"
    Moveable =0
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =16053492
    DatasheetGridlinesColor12 =15062992
    FitToScreen =1
    Begin
        Begin Label
            BackStyle =0
            FontSize =11
            FontName ="Calibri"
        End
        Begin TextBox
            FELineBreak = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            BorderColor =12632256
            FontName ="Calibri"
            AsianLineBreak =1
        End
        Begin EmptyCell
            Height =240
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin Section
            Height =2535
            Name ="Detail"
            Begin
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4410
                    Top =1140
                    Width =1740
                    Height =285
                    FontSize =10
                    TabIndex =13
                    Name ="TRANSMISSION"
                    ControlSource ="TRANSMISSION"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4410
                    LayoutCachedTop =1140
                    LayoutCachedWidth =6150
                    LayoutCachedHeight =1425
                    RowStart =4
                    RowEnd =4
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =3210
                            Top =1140
                            Width =1200
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label0"
                            Caption ="TRANSMISSION"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3210
                            LayoutCachedTop =1140
                            LayoutCachedWidth =4410
                            LayoutCachedHeight =1425
                            RowStart =4
                            RowEnd =4
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4410
                    Top =285
                    Width =1740
                    Height =285
                    FontSize =10
                    TabIndex =4
                    Name ="VEHICLE_CLASS"
                    ControlSource ="VEHICLECLASS"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4410
                    LayoutCachedTop =285
                    LayoutCachedWidth =6150
                    LayoutCachedHeight =570
                    RowStart =1
                    RowEnd =1
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =3210
                            Top =285
                            Width =1200
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label1"
                            Caption ="CLASS:"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3210
                            LayoutCachedTop =285
                            LayoutCachedWidth =4410
                            LayoutCachedHeight =570
                            RowStart =1
                            RowEnd =1
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =960
                    Top =570
                    Width =2250
                    Height =285
                    FontSize =10
                    TabIndex =6
                    Name ="CAB_TYPE"
                    ControlSource ="CABTYPE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =960
                    LayoutCachedTop =570
                    LayoutCachedWidth =3210
                    LayoutCachedHeight =855
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =90
                            Top =570
                            Width =870
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label3"
                            Caption ="CAB TYPE"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =90
                            LayoutCachedTop =570
                            LayoutCachedWidth =960
                            LayoutCachedHeight =855
                            RowStart =2
                            RowEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4410
                    Top =570
                    Width =1740
                    Height =285
                    FontSize =10
                    TabIndex =7
                    Name ="CHASSIS"
                    ControlSource ="CHASSIS"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4410
                    LayoutCachedTop =570
                    LayoutCachedWidth =6150
                    LayoutCachedHeight =855
                    RowStart =2
                    RowEnd =2
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =95
                            TextAlign =1
                            Left =3210
                            Top =570
                            Width =1200
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label4"
                            Caption ="CHASSIS"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3210
                            LayoutCachedTop =570
                            LayoutCachedWidth =4410
                            LayoutCachedHeight =855
                            RowStart =2
                            RowEnd =2
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7560
                    Top =285
                    Width =2490
                    Height =285
                    FontSize =10
                    TabIndex =5
                    Name ="ENGINE_TYPE"
                    ControlSource ="ENGINETYPE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7560
                    LayoutCachedTop =285
                    LayoutCachedWidth =10050
                    LayoutCachedHeight =570
                    RowStart =1
                    RowEnd =1
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =6405
                            Top =285
                            Width =1155
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label5"
                            Caption ="ENGINE_TYPE"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6405
                            LayoutCachedTop =285
                            LayoutCachedWidth =7560
                            LayoutCachedHeight =570
                            RowStart =1
                            RowEnd =1
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4410
                    Top =855
                    Width =1740
                    Height =285
                    FontSize =10
                    TabIndex =10
                    Name ="FUEL_TYPE"
                    ControlSource ="FUELTYPE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4410
                    LayoutCachedTop =855
                    LayoutCachedWidth =6150
                    LayoutCachedHeight =1140
                    RowStart =3
                    RowEnd =3
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =223
                            TextAlign =1
                            Left =3210
                            Top =855
                            Width =1200
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label6"
                            Caption ="FUEL TYPE"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3210
                            LayoutCachedTop =855
                            LayoutCachedWidth =4410
                            LayoutCachedHeight =1140
                            RowStart =3
                            RowEnd =3
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =87
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7560
                    Width =2490
                    Height =285
                    FontSize =10
                    TabIndex =2
                    Name ="ENGINE_MANUFACTURER"
                    ControlSource ="ENGINEMANUFACTURER"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7560
                    LayoutCachedWidth =10050
                    LayoutCachedHeight =285
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =223
                            TextAlign =1
                            Left =6405
                            Width =1155
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label7"
                            Caption ="ENGINE MFG"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6405
                            LayoutCachedWidth =7560
                            LayoutCachedHeight =285
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    TextAlign =1
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7560
                    Top =570
                    Width =2490
                    Height =285
                    FontSize =10
                    TabIndex =8
                    Name ="ENGINE_SERIES_CODE"
                    ControlSource ="ENGINESERIESCODE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7560
                    LayoutCachedTop =570
                    LayoutCachedWidth =10050
                    LayoutCachedHeight =855
                    RowStart =2
                    RowEnd =2
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =95
                            TextAlign =1
                            Left =6405
                            Top =570
                            Width =1155
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label8"
                            Caption ="ENG SERIES"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6405
                            LayoutCachedTop =570
                            LayoutCachedWidth =7560
                            LayoutCachedHeight =855
                            RowStart =2
                            RowEnd =2
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =960
                    Top =855
                    Width =2250
                    Height =285
                    FontSize =10
                    TabIndex =9
                    Name ="DRIVE_LINE_TYPE"
                    ControlSource ="DRIVELINETYPE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =960
                    LayoutCachedTop =855
                    LayoutCachedWidth =3210
                    LayoutCachedHeight =1140
                    RowStart =3
                    RowEnd =3
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =95
                            TextAlign =1
                            Left =90
                            Top =855
                            Width =870
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label9"
                            Caption ="Axles"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =90
                            LayoutCachedTop =855
                            LayoutCachedWidth =960
                            LayoutCachedHeight =1140
                            RowStart =3
                            RowEnd =3
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =960
                    Top =1140
                    Width =2250
                    Height =285
                    FontSize =10
                    TabIndex =12
                    Name ="GVWR_CLASS"
                    ControlSource ="GVWRCLASS"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =960
                    LayoutCachedTop =1140
                    LayoutCachedWidth =3210
                    LayoutCachedHeight =1425
                    RowStart =4
                    RowEnd =4
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =95
                            TextAlign =1
                            Left =90
                            Top =1140
                            Width =870
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label13"
                            Caption ="GVWR"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =90
                            LayoutCachedTop =1140
                            LayoutCachedWidth =960
                            LayoutCachedHeight =1425
                            RowStart =4
                            RowEnd =4
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    TextAlign =1
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7560
                    Top =855
                    Width =2490
                    Height =285
                    FontSize =10
                    TabIndex =11
                    Name ="ENGINE_MODIFIER"
                    ControlSource ="ENGINEMODIFIER"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7560
                    LayoutCachedTop =855
                    LayoutCachedWidth =10050
                    LayoutCachedHeight =1140
                    RowStart =3
                    RowEnd =3
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =95
                            TextAlign =1
                            Left =6405
                            Top =855
                            Width =1155
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label15"
                            Caption ="MODIFIER"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6405
                            LayoutCachedTop =855
                            LayoutCachedWidth =7560
                            LayoutCachedHeight =1140
                            RowStart =3
                            RowEnd =3
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    TextAlign =1
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7560
                    Top =1710
                    Width =2490
                    Height =285
                    FontSize =10
                    TabIndex =18
                    Name ="HYBRID_TYPE"
                    ControlSource ="HYBRIDTYPE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7560
                    LayoutCachedTop =1710
                    LayoutCachedWidth =10050
                    LayoutCachedHeight =1995
                    RowStart =6
                    RowEnd =6
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =6405
                            Top =1710
                            Width =1155
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label19"
                            Caption ="HYBRID TYPE:"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6405
                            LayoutCachedTop =1710
                            LayoutCachedWidth =7560
                            LayoutCachedHeight =1995
                            RowStart =6
                            RowEnd =6
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    Locked = NotDefault
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =960
                    Width =2250
                    Height =285
                    FontSize =10
                    FontWeight =700
                    Name ="MODEL_YEAR"
                    ControlSource ="MODELYEAR"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =960
                    LayoutCachedWidth =3210
                    LayoutCachedHeight =285
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =90
                            Width =870
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label23"
                            Caption ="MODEL YR"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =90
                            LayoutCachedWidth =960
                            LayoutCachedHeight =285
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    TextAlign =2
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7560
                    Top =1140
                    Width =2490
                    Height =285
                    FontSize =10
                    FontWeight =700
                    TabIndex =14
                    Name ="ENGINE_CODE"
                    ControlSource ="ENGINECODE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7560
                    LayoutCachedTop =1140
                    LayoutCachedWidth =10050
                    LayoutCachedHeight =1425
                    RowStart =4
                    RowEnd =4
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =95
                            TextAlign =1
                            Left =6405
                            Top =1140
                            Width =1155
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label27"
                            Caption ="ENGINE CODE"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6405
                            LayoutCachedTop =1140
                            LayoutCachedWidth =7560
                            LayoutCachedHeight =1425
                            RowStart =4
                            RowEnd =4
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4410
                    Top =1710
                    Width =1740
                    Height =285
                    FontSize =10
                    FontWeight =700
                    TabIndex =17
                    Name ="COUNTRY"
                    ControlSource ="COUNTRY"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4410
                    LayoutCachedTop =1710
                    LayoutCachedWidth =6150
                    LayoutCachedHeight =1995
                    RowStart =6
                    RowEnd =6
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =3210
                            Top =1710
                            Width =1200
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label28"
                            Caption ="COUNTRY"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3210
                            LayoutCachedTop =1710
                            LayoutCachedWidth =4410
                            LayoutCachedHeight =1995
                            RowStart =6
                            RowEnd =6
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4410
                    Top =1425
                    Width =1740
                    Height =285
                    FontSize =10
                    TabIndex =15
                    Name ="ASSY_PLANT"
                    ControlSource ="ASSYPLANT"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4410
                    LayoutCachedTop =1425
                    LayoutCachedWidth =6150
                    LayoutCachedHeight =1710
                    RowStart =5
                    RowEnd =5
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =223
                            TextAlign =1
                            Left =3210
                            Top =1425
                            Width =1200
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label29"
                            Caption ="ASSY PLANT"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3210
                            LayoutCachedTop =1425
                            LayoutCachedWidth =4410
                            LayoutCachedHeight =1710
                            RowStart =5
                            RowEnd =5
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    Locked = NotDefault
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4410
                    Width =1740
                    Height =285
                    FontSize =10
                    TabIndex =1
                    Name ="MAKE"
                    ControlSource ="MAKE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4410
                    LayoutCachedWidth =6150
                    LayoutCachedHeight =285
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =223
                            TextAlign =1
                            Left =3210
                            Width =1200
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label30"
                            Caption ="MAKE"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3210
                            LayoutCachedWidth =4410
                            LayoutCachedHeight =285
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =87
                    BackStyle =0
                    IMESentenceMode =3
                    Left =960
                    Top =285
                    Width =2250
                    Height =285
                    FontSize =10
                    TabIndex =3
                    Name ="MODEL"
                    ControlSource ="MODEL"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =960
                    LayoutCachedTop =285
                    LayoutCachedWidth =3210
                    LayoutCachedHeight =570
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =223
                            TextAlign =1
                            Left =90
                            Top =285
                            Width =870
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label31"
                            Caption ="MODEL"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =90
                            LayoutCachedTop =285
                            LayoutCachedWidth =960
                            LayoutCachedHeight =570
                            RowStart =1
                            RowEnd =1
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    Visible = NotDefault
                    OverlapFlags =93
                    TextFontCharSet =163
                    TextAlign =1
                    IMESentenceMode =3
                    Left =10080
                    Top =1710
                    Width =255
                    Height =285
                    FontSize =8
                    TabIndex =19
                    ForeColor =5026082
                    Name ="UNITID"
                    ControlSource ="UNITID"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =10080
                    LayoutCachedTop =1710
                    LayoutCachedWidth =10335
                    LayoutCachedHeight =1995
                    RowStart =6
                    RowEnd =6
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    SpecialEffect =5
                    OverlapFlags =87
                    TextAlign =2
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7560
                    Top =1425
                    Width =2490
                    Height =285
                    FontSize =10
                    FontWeight =700
                    TabIndex =16
                    Name ="HORSEPOWER"
                    ControlSource ="HORSEPOWER"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7560
                    LayoutCachedTop =1425
                    LayoutCachedWidth =10050
                    LayoutCachedHeight =1710
                    RowStart =5
                    RowEnd =5
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =223
                            TextAlign =1
                            Left =6405
                            Top =1425
                            Width =1155
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label33"
                            Caption ="HORSEPOWER:"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6405
                            LayoutCachedTop =1425
                            LayoutCachedWidth =7560
                            LayoutCachedHeight =1710
                            RowStart =5
                            RowEnd =5
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin EmptyCell
                    Left =10080
                    Top =1140
                    Width =255
                    Height =285
                    Name ="EmptyCell84"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10080
                    LayoutCachedTop =1140
                    LayoutCachedWidth =10335
                    LayoutCachedHeight =1425
                    RowStart =4
                    RowEnd =4
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =90
                    Top =1710
                    Width =870
                    Height =285
                    Name ="EmptyCell98"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =90
                    LayoutCachedTop =1710
                    LayoutCachedWidth =960
                    LayoutCachedHeight =1995
                    RowStart =6
                    RowEnd =6
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10080
                    Top =1425
                    Width =255
                    Height =285
                    Name ="EmptyCell117"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10080
                    LayoutCachedTop =1425
                    LayoutCachedWidth =10335
                    LayoutCachedHeight =1710
                    RowStart =5
                    RowEnd =5
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10080
                    Top =570
                    Width =255
                    Height =285
                    Name ="EmptyCell126"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10080
                    LayoutCachedTop =570
                    LayoutCachedWidth =10335
                    LayoutCachedHeight =855
                    RowStart =2
                    RowEnd =2
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10080
                    Width =255
                    Height =285
                    Name ="EmptyCell144"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10080
                    LayoutCachedWidth =10335
                    LayoutCachedHeight =285
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6150
                    Top =570
                    Width =255
                    Height =285
                    Name ="EmptyCell154"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6150
                    LayoutCachedTop =570
                    LayoutCachedWidth =6405
                    LayoutCachedHeight =855
                    RowStart =2
                    RowEnd =2
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6150
                    Top =1140
                    Width =255
                    Height =285
                    Name ="EmptyCell155"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6150
                    LayoutCachedTop =1140
                    LayoutCachedWidth =6405
                    LayoutCachedHeight =1425
                    RowStart =4
                    RowEnd =4
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6150
                    Top =1425
                    Width =255
                    Height =285
                    Name ="EmptyCell156"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6150
                    LayoutCachedTop =1425
                    LayoutCachedWidth =6405
                    LayoutCachedHeight =1710
                    RowStart =5
                    RowEnd =5
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6150
                    Top =1710
                    Width =255
                    Height =285
                    Name ="EmptyCell157"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6150
                    LayoutCachedTop =1710
                    LayoutCachedWidth =6405
                    LayoutCachedHeight =1995
                    RowStart =6
                    RowEnd =6
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10080
                    Top =285
                    Width =255
                    Height =285
                    Name ="EmptyCell160"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10080
                    LayoutCachedTop =285
                    LayoutCachedWidth =10335
                    LayoutCachedHeight =570
                    RowStart =1
                    RowEnd =1
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6150
                    Top =855
                    Width =255
                    Height =285
                    Name ="EmptyCell185"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6150
                    LayoutCachedTop =855
                    LayoutCachedWidth =6405
                    LayoutCachedHeight =1140
                    RowStart =3
                    RowEnd =3
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10080
                    Top =855
                    Width =255
                    Height =285
                    Name ="EmptyCell190"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10080
                    LayoutCachedTop =855
                    LayoutCachedWidth =10335
                    LayoutCachedHeight =1140
                    RowStart =3
                    RowEnd =3
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6150
                    Width =255
                    Height =285
                    Name ="EmptyCell213"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6150
                    LayoutCachedWidth =6405
                    LayoutCachedHeight =285
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6150
                    Top =285
                    Width =255
                    Height =285
                    Name ="EmptyCell215"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6150
                    LayoutCachedTop =285
                    LayoutCachedWidth =6405
                    LayoutCachedHeight =570
                    RowStart =1
                    RowEnd =1
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =960
                    Top =1995
                    Width =5190
                    Height =480
                    FontSize =10
                    TabIndex =20
                    Name ="Text269"
                    ControlSource ="description"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =960
                    LayoutCachedTop =1995
                    LayoutCachedWidth =6150
                    LayoutCachedHeight =2475
                    RowStart =7
                    RowEnd =8
                    ColumnStart =1
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =90
                            Top =1995
                            Width =870
                            Height =240
                            FontSize =8
                            FontWeight =700
                            Name ="Label270"
                            Caption ="Note"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =90
                            LayoutCachedTop =1995
                            LayoutCachedWidth =960
                            LayoutCachedHeight =2235
                            RowStart =7
                            RowEnd =7
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin EmptyCell
                    Left =6150
                    Top =1995
                    Width =255
                    Name ="EmptyCell277"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6150
                    LayoutCachedTop =1995
                    LayoutCachedWidth =6405
                    LayoutCachedHeight =2235
                    RowStart =7
                    RowEnd =7
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6405
                    Top =1995
                    Width =1155
                    Name ="EmptyCell278"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6405
                    LayoutCachedTop =1995
                    LayoutCachedWidth =7560
                    LayoutCachedHeight =2235
                    RowStart =7
                    RowEnd =7
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =7560
                    Top =1995
                    Width =2490
                    Name ="EmptyCell279"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =7560
                    LayoutCachedTop =1995
                    LayoutCachedWidth =10050
                    LayoutCachedHeight =2235
                    RowStart =7
                    RowEnd =7
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10080
                    Top =1995
                    Width =255
                    Name ="EmptyCell280"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10080
                    LayoutCachedTop =1995
                    LayoutCachedWidth =10335
                    LayoutCachedHeight =2235
                    RowStart =7
                    RowEnd =7
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =90
                    Top =1425
                    Width =870
                    Height =285
                    Name ="EmptyCell281"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =90
                    LayoutCachedTop =1425
                    LayoutCachedWidth =960
                    LayoutCachedHeight =1710
                    RowStart =5
                    RowEnd =5
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =960
                    Top =1425
                    Width =2250
                    Height =570
                    Name ="EmptyCell282"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =960
                    LayoutCachedTop =1425
                    LayoutCachedWidth =3210
                    LayoutCachedHeight =1995
                    RowStart =5
                    RowEnd =6
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =90
                    Top =2235
                    Width =870
                    Name ="EmptyCell283"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =90
                    LayoutCachedTop =2235
                    LayoutCachedWidth =960
                    LayoutCachedHeight =2475
                    RowStart =8
                    RowEnd =8
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6150
                    Top =2235
                    Width =255
                    Name ="EmptyCell287"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6150
                    LayoutCachedTop =2235
                    LayoutCachedWidth =6405
                    LayoutCachedHeight =2475
                    RowStart =8
                    RowEnd =8
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6405
                    Top =2235
                    Width =1155
                    Name ="EmptyCell288"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6405
                    LayoutCachedTop =2235
                    LayoutCachedWidth =7560
                    LayoutCachedHeight =2475
                    RowStart =8
                    RowEnd =8
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =7560
                    Top =2235
                    Width =2490
                    Name ="EmptyCell289"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =7560
                    LayoutCachedTop =2235
                    LayoutCachedWidth =10050
                    LayoutCachedHeight =2475
                    RowStart =8
                    RowEnd =8
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10080
                    Top =2235
                    Width =255
                    Name ="EmptyCell290"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10080
                    LayoutCachedTop =2235
                    LayoutCachedWidth =10335
                    LayoutCachedHeight =2475
                    RowStart =8
                    RowEnd =8
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
            End
        End
    End
End
CodeBehindForm
' See "VINDecode.cls"
