Version =20
VersionRequired =20
Begin Form
    PopUp = NotDefault
    RecordSelectors = NotDefault
    MaxButton = NotDefault
    MinButton = NotDefault
    ControlBox = NotDefault
    NavigationButtons = NotDefault
    CloseButton = NotDefault
    DividingLines = NotDefault
    AllowEdits = NotDefault
    AllowDesignChanges = NotDefault
    DefaultView =0
    ScrollBars =0
    TabularCharSet =163
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridX =24
    GridY =24
    Width =11580
    DatasheetFontHeight =11
    ItemSuffix =291
    Left =5235
    Top =13800
    Right =16215
    Bottom =17400
    ShortcutMenuBar ="SortClip"
    RecSrcDt = Begin
        0x35d4eddad297e540
    End
    OnClose ="[Event Procedure]"
    DatasheetFontName ="Calibri"
    Moveable =0
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =16053492
    DatasheetGridlinesColor12 =15062992
    FitToScreen =1
    Begin
        Begin Label
            BackStyle =0
            FontSize =11
            FontName ="Calibri"
        End
        Begin TextBox
            FELineBreak = NotDefault
            BorderLineStyle =0
            LabelX =-1800
            FontSize =11
            BorderColor =12632256
            FontName ="Calibri"
            AsianLineBreak =1
        End
        Begin EmptyCell
            Height =240
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin Section
            Height =2535
            Name ="Detail"
            Begin
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4428
                    Top =1152
                    Width =1740
                    Height =288
                    FontSize =10
                    TabIndex =13
                    Name ="TRANSMISSION"
                    ControlSource ="TRANSMISSION"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4428
                    LayoutCachedTop =1152
                    LayoutCachedWidth =6168
                    LayoutCachedHeight =1440
                    RowStart =4
                    RowEnd =4
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =3228
                            Top =1152
                            Width =1200
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label0"
                            Caption ="TRANSMISSION"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3228
                            LayoutCachedTop =1152
                            LayoutCachedWidth =4428
                            LayoutCachedHeight =1440
                            RowStart =4
                            RowEnd =4
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4428
                    Top =288
                    Width =1740
                    Height =288
                    FontSize =10
                    TabIndex =4
                    Name ="VEHICLE_CLASS"
                    ControlSource ="VEHICLECLASS"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4428
                    LayoutCachedTop =288
                    LayoutCachedWidth =6168
                    LayoutCachedHeight =576
                    RowStart =1
                    RowEnd =1
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =3228
                            Top =288
                            Width =1200
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label1"
                            Caption ="CLASS:"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3228
                            LayoutCachedTop =288
                            LayoutCachedWidth =4428
                            LayoutCachedHeight =576
                            RowStart =1
                            RowEnd =1
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =972
                    Top =576
                    Width =2256
                    Height =288
                    FontSize =10
                    TabIndex =6
                    Name ="CAB_TYPE"
                    ControlSource ="CABTYPE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =972
                    LayoutCachedTop =576
                    LayoutCachedWidth =3228
                    LayoutCachedHeight =864
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =96
                            Top =576
                            Width =876
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label3"
                            Caption ="CAB TYPE"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =96
                            LayoutCachedTop =576
                            LayoutCachedWidth =972
                            LayoutCachedHeight =864
                            RowStart =2
                            RowEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4428
                    Top =576
                    Width =1740
                    Height =288
                    FontSize =10
                    TabIndex =7
                    Name ="CHASSIS"
                    ControlSource ="CHASSIS"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4428
                    LayoutCachedTop =576
                    LayoutCachedWidth =6168
                    LayoutCachedHeight =864
                    RowStart =2
                    RowEnd =2
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =95
                            TextAlign =1
                            Left =3228
                            Top =576
                            Width =1200
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label4"
                            Caption ="CHASSIS"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3228
                            LayoutCachedTop =576
                            LayoutCachedWidth =4428
                            LayoutCachedHeight =864
                            RowStart =2
                            RowEnd =2
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7572
                    Top =288
                    Width =2496
                    Height =288
                    FontSize =10
                    TabIndex =5
                    Name ="ENGINE_TYPE"
                    ControlSource ="ENGINETYPE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7572
                    LayoutCachedTop =288
                    LayoutCachedWidth =10068
                    LayoutCachedHeight =576
                    RowStart =1
                    RowEnd =1
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =6420
                            Top =288
                            Width =1152
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label5"
                            Caption ="ENGINE_TYPE"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6420
                            LayoutCachedTop =288
                            LayoutCachedWidth =7572
                            LayoutCachedHeight =576
                            RowStart =1
                            RowEnd =1
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4428
                    Top =864
                    Width =1740
                    Height =288
                    FontSize =10
                    TabIndex =10
                    Name ="FUEL_TYPE"
                    ControlSource ="FUELTYPE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4428
                    LayoutCachedTop =864
                    LayoutCachedWidth =6168
                    LayoutCachedHeight =1152
                    RowStart =3
                    RowEnd =3
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =223
                            TextAlign =1
                            Left =3228
                            Top =864
                            Width =1200
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label6"
                            Caption ="FUEL TYPE"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3228
                            LayoutCachedTop =864
                            LayoutCachedWidth =4428
                            LayoutCachedHeight =1152
                            RowStart =3
                            RowEnd =3
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =87
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7572
                    Width =2496
                    Height =285
                    FontSize =10
                    TabIndex =2
                    Name ="ENGINE_MANUFACTURER"
                    ControlSource ="ENGINEMANUFACTURER"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7572
                    LayoutCachedWidth =10068
                    LayoutCachedHeight =285
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =223
                            TextAlign =1
                            Left =6420
                            Width =1152
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label7"
                            Caption ="ENGINE MFG"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6420
                            LayoutCachedWidth =7572
                            LayoutCachedHeight =285
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    TextAlign =1
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7572
                    Top =576
                    Width =2496
                    Height =288
                    FontSize =10
                    TabIndex =8
                    Name ="ENGINE_SERIES_CODE"
                    ControlSource ="ENGINESERIESCODE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7572
                    LayoutCachedTop =576
                    LayoutCachedWidth =10068
                    LayoutCachedHeight =864
                    RowStart =2
                    RowEnd =2
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =95
                            TextAlign =1
                            Left =6420
                            Top =576
                            Width =1152
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label8"
                            Caption ="ENG SERIES"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6420
                            LayoutCachedTop =576
                            LayoutCachedWidth =7572
                            LayoutCachedHeight =864
                            RowStart =2
                            RowEnd =2
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =972
                    Top =864
                    Width =2256
                    Height =288
                    FontSize =10
                    TabIndex =9
                    Name ="DRIVE_LINE_TYPE"
                    ControlSource ="DRIVELINETYPE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =972
                    LayoutCachedTop =864
                    LayoutCachedWidth =3228
                    LayoutCachedHeight =1152
                    RowStart =3
                    RowEnd =3
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =95
                            TextAlign =1
                            Left =96
                            Top =864
                            Width =876
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label9"
                            Caption ="Axles"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =96
                            LayoutCachedTop =864
                            LayoutCachedWidth =972
                            LayoutCachedHeight =1152
                            RowStart =3
                            RowEnd =3
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =972
                    Top =1152
                    Width =2256
                    Height =288
                    FontSize =10
                    TabIndex =12
                    Name ="GVWR_CLASS"
                    ControlSource ="GVWRCLASS"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =972
                    LayoutCachedTop =1152
                    LayoutCachedWidth =3228
                    LayoutCachedHeight =1440
                    RowStart =4
                    RowEnd =4
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =95
                            TextAlign =1
                            Left =96
                            Top =1152
                            Width =876
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label13"
                            Caption ="GVWR"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =96
                            LayoutCachedTop =1152
                            LayoutCachedWidth =972
                            LayoutCachedHeight =1440
                            RowStart =4
                            RowEnd =4
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    TextAlign =1
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7572
                    Top =864
                    Width =2496
                    Height =288
                    FontSize =10
                    TabIndex =11
                    Name ="ENGINE_MODIFIER"
                    ControlSource ="ENGINEMODIFIER"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7572
                    LayoutCachedTop =864
                    LayoutCachedWidth =10068
                    LayoutCachedHeight =1152
                    RowStart =3
                    RowEnd =3
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =95
                            TextAlign =1
                            Left =6420
                            Top =864
                            Width =1152
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label15"
                            Caption ="MODIFIER"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6420
                            LayoutCachedTop =864
                            LayoutCachedWidth =7572
                            LayoutCachedHeight =1152
                            RowStart =3
                            RowEnd =3
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    TextAlign =1
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7572
                    Top =1740
                    Width =2496
                    Height =288
                    FontSize =10
                    TabIndex =18
                    Name ="HYBRID_TYPE"
                    ControlSource ="HYBRIDTYPE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7572
                    LayoutCachedTop =1740
                    LayoutCachedWidth =10068
                    LayoutCachedHeight =2028
                    RowStart =6
                    RowEnd =6
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =6420
                            Top =1740
                            Width =1152
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label19"
                            Caption ="HYBRID TYPE:"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6420
                            LayoutCachedTop =1740
                            LayoutCachedWidth =7572
                            LayoutCachedHeight =2028
                            RowStart =6
                            RowEnd =6
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    Locked = NotDefault
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =972
                    Width =2256
                    Height =285
                    FontSize =10
                    FontWeight =700
                    Name ="MODEL_YEAR"
                    ControlSource ="MODELYEAR"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =972
                    LayoutCachedWidth =3228
                    LayoutCachedHeight =285
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =96
                            Width =876
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label23"
                            Caption ="MODEL YR"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =96
                            LayoutCachedWidth =972
                            LayoutCachedHeight =285
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    TextAlign =2
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7572
                    Top =1152
                    Width =2496
                    Height =288
                    FontSize =10
                    FontWeight =700
                    TabIndex =14
                    Name ="ENGINE_CODE"
                    ControlSource ="ENGINECODE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7572
                    LayoutCachedTop =1152
                    LayoutCachedWidth =10068
                    LayoutCachedHeight =1440
                    RowStart =4
                    RowEnd =4
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =95
                            TextAlign =1
                            Left =6420
                            Top =1152
                            Width =1152
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label27"
                            Caption ="ENGINE CODE"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6420
                            LayoutCachedTop =1152
                            LayoutCachedWidth =7572
                            LayoutCachedHeight =1440
                            RowStart =4
                            RowEnd =4
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4428
                    Top =1740
                    Width =1740
                    Height =288
                    FontSize =10
                    FontWeight =700
                    TabIndex =17
                    Name ="COUNTRY"
                    ControlSource ="COUNTRY"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4428
                    LayoutCachedTop =1740
                    LayoutCachedWidth =6168
                    LayoutCachedHeight =2028
                    RowStart =6
                    RowEnd =6
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =3228
                            Top =1740
                            Width =1200
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label28"
                            Caption ="COUNTRY"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3228
                            LayoutCachedTop =1740
                            LayoutCachedWidth =4428
                            LayoutCachedHeight =2028
                            RowStart =6
                            RowEnd =6
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4428
                    Top =1440
                    Width =1740
                    Height =288
                    FontSize =10
                    TabIndex =15
                    Name ="ASSY_PLANT"
                    ControlSource ="ASSYPLANT"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4428
                    LayoutCachedTop =1440
                    LayoutCachedWidth =6168
                    LayoutCachedHeight =1728
                    RowStart =5
                    RowEnd =5
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =223
                            TextAlign =1
                            Left =3228
                            Top =1440
                            Width =1200
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label29"
                            Caption ="ASSY PLANT"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3228
                            LayoutCachedTop =1440
                            LayoutCachedWidth =4428
                            LayoutCachedHeight =1728
                            RowStart =5
                            RowEnd =5
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    Locked = NotDefault
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =4428
                    Width =1740
                    Height =285
                    FontSize =10
                    TabIndex =1
                    Name ="MAKE"
                    ControlSource ="MAKE"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =4428
                    LayoutCachedWidth =6168
                    LayoutCachedHeight =285
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =223
                            TextAlign =1
                            Left =3228
                            Width =1200
                            Height =285
                            FontSize =8
                            FontWeight =700
                            Name ="Label30"
                            Caption ="MAKE"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =3228
                            LayoutCachedWidth =4428
                            LayoutCachedHeight =285
                            ColumnStart =2
                            ColumnEnd =2
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =87
                    BackStyle =0
                    IMESentenceMode =3
                    Left =972
                    Top =288
                    Width =2256
                    Height =288
                    FontSize =10
                    TabIndex =3
                    Name ="MODEL"
                    ControlSource ="MODEL"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =972
                    LayoutCachedTop =288
                    LayoutCachedWidth =3228
                    LayoutCachedHeight =576
                    RowStart =1
                    RowEnd =1
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =223
                            TextAlign =1
                            Left =96
                            Top =288
                            Width =876
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label31"
                            Caption ="MODEL"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =96
                            LayoutCachedTop =288
                            LayoutCachedWidth =972
                            LayoutCachedHeight =576
                            RowStart =1
                            RowEnd =1
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin TextBox
                    Visible = NotDefault
                    OverlapFlags =93
                    TextFontCharSet =163
                    TextAlign =1
                    IMESentenceMode =3
                    Left =10104
                    Top =1740
                    Width =252
                    Height =288
                    FontSize =8
                    TabIndex =19
                    ForeColor =5026082
                    Name ="UNITID"
                    ControlSource ="UNITID"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =10104
                    LayoutCachedTop =1740
                    LayoutCachedWidth =10356
                    LayoutCachedHeight =2028
                    RowStart =6
                    RowEnd =6
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                End
                Begin TextBox
                    Locked = NotDefault
                    SpecialEffect =5
                    OverlapFlags =87
                    TextAlign =2
                    BackStyle =0
                    IMESentenceMode =3
                    Left =7572
                    Top =1440
                    Width =2496
                    Height =288
                    FontSize =10
                    FontWeight =700
                    TabIndex =16
                    Name ="HORSEPOWER"
                    ControlSource ="HORSEPOWER"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =7572
                    LayoutCachedTop =1440
                    LayoutCachedWidth =10068
                    LayoutCachedHeight =1728
                    RowStart =5
                    RowEnd =5
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =223
                            TextAlign =1
                            Left =6420
                            Top =1440
                            Width =1152
                            Height =288
                            FontSize =8
                            FontWeight =700
                            Name ="Label33"
                            Caption ="HORSEPOWER:"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =6420
                            LayoutCachedTop =1440
                            LayoutCachedWidth =7572
                            LayoutCachedHeight =1728
                            RowStart =5
                            RowEnd =5
                            ColumnStart =5
                            ColumnEnd =5
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin EmptyCell
                    Left =10104
                    Top =1152
                    Width =252
                    Height =288
                    Name ="EmptyCell84"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10104
                    LayoutCachedTop =1152
                    LayoutCachedWidth =10356
                    LayoutCachedHeight =1440
                    RowStart =4
                    RowEnd =4
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =96
                    Top =1740
                    Width =876
                    Height =288
                    Name ="EmptyCell98"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =96
                    LayoutCachedTop =1740
                    LayoutCachedWidth =972
                    LayoutCachedHeight =2028
                    RowStart =6
                    RowEnd =6
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10104
                    Top =1440
                    Width =252
                    Height =288
                    Name ="EmptyCell117"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10104
                    LayoutCachedTop =1440
                    LayoutCachedWidth =10356
                    LayoutCachedHeight =1728
                    RowStart =5
                    RowEnd =5
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10104
                    Top =576
                    Width =252
                    Height =288
                    Name ="EmptyCell126"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10104
                    LayoutCachedTop =576
                    LayoutCachedWidth =10356
                    LayoutCachedHeight =864
                    RowStart =2
                    RowEnd =2
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10104
                    Width =252
                    Height =285
                    Name ="EmptyCell144"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10104
                    LayoutCachedWidth =10356
                    LayoutCachedHeight =285
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6168
                    Top =576
                    Width =252
                    Height =288
                    Name ="EmptyCell154"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6168
                    LayoutCachedTop =576
                    LayoutCachedWidth =6420
                    LayoutCachedHeight =864
                    RowStart =2
                    RowEnd =2
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6168
                    Top =1152
                    Width =252
                    Height =288
                    Name ="EmptyCell155"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6168
                    LayoutCachedTop =1152
                    LayoutCachedWidth =6420
                    LayoutCachedHeight =1440
                    RowStart =4
                    RowEnd =4
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6168
                    Top =1440
                    Width =252
                    Height =288
                    Name ="EmptyCell156"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6168
                    LayoutCachedTop =1440
                    LayoutCachedWidth =6420
                    LayoutCachedHeight =1728
                    RowStart =5
                    RowEnd =5
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6168
                    Top =1740
                    Width =252
                    Height =288
                    Name ="EmptyCell157"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6168
                    LayoutCachedTop =1740
                    LayoutCachedWidth =6420
                    LayoutCachedHeight =2028
                    RowStart =6
                    RowEnd =6
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10104
                    Top =288
                    Width =252
                    Height =288
                    Name ="EmptyCell160"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10104
                    LayoutCachedTop =288
                    LayoutCachedWidth =10356
                    LayoutCachedHeight =576
                    RowStart =1
                    RowEnd =1
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6168
                    Top =864
                    Width =252
                    Height =288
                    Name ="EmptyCell185"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6168
                    LayoutCachedTop =864
                    LayoutCachedWidth =6420
                    LayoutCachedHeight =1152
                    RowStart =3
                    RowEnd =3
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10104
                    Top =864
                    Width =252
                    Height =288
                    Name ="EmptyCell190"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10104
                    LayoutCachedTop =864
                    LayoutCachedWidth =10356
                    LayoutCachedHeight =1152
                    RowStart =3
                    RowEnd =3
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6168
                    Width =252
                    Height =285
                    Name ="EmptyCell213"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6168
                    LayoutCachedWidth =6420
                    LayoutCachedHeight =285
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6168
                    Top =288
                    Width =252
                    Height =288
                    Name ="EmptyCell215"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6168
                    LayoutCachedTop =288
                    LayoutCachedWidth =6420
                    LayoutCachedHeight =576
                    RowStart =1
                    RowEnd =1
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin TextBox
                    SpecialEffect =5
                    OverlapFlags =95
                    BackStyle =0
                    IMESentenceMode =3
                    Left =972
                    Top =2028
                    Width =5196
                    Height =480
                    FontSize =10
                    TabIndex =20
                    Name ="Text269"
                    ControlSource ="description"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0

                    LayoutCachedLeft =972
                    LayoutCachedTop =2028
                    LayoutCachedWidth =6168
                    LayoutCachedHeight =2508
                    RowStart =7
                    RowEnd =8
                    ColumnStart =1
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    ThemeFontIndex =1
                    GridlineThemeColorIndex =1
                    GridlineShade =65.0
                    GroupTable =2
                    Begin
                        Begin Label
                            OverlapFlags =93
                            TextAlign =1
                            Left =96
                            Top =2028
                            Width =876
                            Height =240
                            FontSize =8
                            FontWeight =700
                            Name ="Label270"
                            Caption ="Note"
                            GroupTable =2
                            LeftPadding =0
                            TopPadding =0
                            RightPadding =0
                            BottomPadding =0
                            LayoutCachedLeft =96
                            LayoutCachedTop =2028
                            LayoutCachedWidth =972
                            LayoutCachedHeight =2268
                            RowStart =7
                            RowEnd =7
                            LayoutGroup =1
                            ThemeFontIndex =1
                            ForeThemeColorIndex =2
                            GridlineThemeColorIndex =1
                            GridlineShade =65.0
                            GroupTable =2
                        End
                    End
                End
                Begin EmptyCell
                    Left =6168
                    Top =2028
                    Width =252
                    Name ="EmptyCell277"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6168
                    LayoutCachedTop =2028
                    LayoutCachedWidth =6420
                    LayoutCachedHeight =2268
                    RowStart =7
                    RowEnd =7
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6420
                    Top =2028
                    Width =1152
                    Name ="EmptyCell278"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6420
                    LayoutCachedTop =2028
                    LayoutCachedWidth =7572
                    LayoutCachedHeight =2268
                    RowStart =7
                    RowEnd =7
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =7572
                    Top =2028
                    Width =2496
                    Name ="EmptyCell279"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =7572
                    LayoutCachedTop =2028
                    LayoutCachedWidth =10068
                    LayoutCachedHeight =2268
                    RowStart =7
                    RowEnd =7
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10104
                    Top =2028
                    Width =252
                    Name ="EmptyCell280"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10104
                    LayoutCachedTop =2028
                    LayoutCachedWidth =10356
                    LayoutCachedHeight =2268
                    RowStart =7
                    RowEnd =7
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =96
                    Top =1440
                    Width =876
                    Height =288
                    Name ="EmptyCell281"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =96
                    LayoutCachedTop =1440
                    LayoutCachedWidth =972
                    LayoutCachedHeight =1728
                    RowStart =5
                    RowEnd =5
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =972
                    Top =1440
                    Width =2256
                    Height =588
                    Name ="EmptyCell282"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =972
                    LayoutCachedTop =1440
                    LayoutCachedWidth =3228
                    LayoutCachedHeight =2028
                    RowStart =5
                    RowEnd =6
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =96
                    Top =2268
                    Width =876
                    Name ="EmptyCell283"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =96
                    LayoutCachedTop =2268
                    LayoutCachedWidth =972
                    LayoutCachedHeight =2508
                    RowStart =8
                    RowEnd =8
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6168
                    Top =2268
                    Width =252
                    Name ="EmptyCell287"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6168
                    LayoutCachedTop =2268
                    LayoutCachedWidth =6420
                    LayoutCachedHeight =2508
                    RowStart =8
                    RowEnd =8
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =6420
                    Top =2268
                    Width =1152
                    Name ="EmptyCell288"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6420
                    LayoutCachedTop =2268
                    LayoutCachedWidth =7572
                    LayoutCachedHeight =2508
                    RowStart =8
                    RowEnd =8
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =7572
                    Top =2268
                    Width =2496
                    Name ="EmptyCell289"
                    GroupTable =2
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =7572
                    LayoutCachedTop =2268
                    LayoutCachedWidth =10068
                    LayoutCachedHeight =2508
                    RowStart =8
                    RowEnd =8
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    GroupTable =2
                End
                Begin EmptyCell
                    Left =10104
                    Top =2268
                    Width =252
                    Name ="EmptyCell290"
                    GroupTable =2
                    TopPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =10104
                    LayoutCachedTop =2268
                    LayoutCachedWidth =10356
                    LayoutCachedHeight =2508
                    RowStart =8
                    RowEnd =8
                    ColumnStart =7
                    ColumnEnd =7
                    LayoutGroup =1
                    GroupTable =2
                End
            End
        End
    End
End
CodeBehindForm
' See "VINDecode.cls"
